import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import test from 'node:test';

test('CMS publishing, version conflicts and private course attachments',async t=>{
  const temp=mkdtempSync(path.join(tmpdir(),'oneshowlearn-cms-test-'));
  Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:path.join(temp,'test.db'),UPLOAD_DIR:path.join(temp,'uploads'),JWT_SECRET:'cms-tests-only'});
  const {db,row,run}=await import('../server/db.mjs');
  const {signUser}=await import('../server/auth.mjs');
  const {createApp}=await import('../server/index.mjs');
  const server=createApp().listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  t.after(async()=>{await new Promise(r=>server.close(r));db.close();rmSync(temp,{recursive:true,force:true});});
  const base=`http://127.0.0.1:${server.address().port}`;
  const user=(name,role)=>{const id=Number(run('INSERT INTO users(email,password_hash,name,role,email_verified) VALUES(?,?,?,?,1)',[`${name}@example.com`,'unused',name,role]).lastInsertRowid);return{id,token:signUser(row('SELECT * FROM users WHERE id=?',[id]))};};
  const admin=user('cms-admin','admin'),editor=user('cms-editor','editor'),learner=user('cms-learner','learner');
  const req=async(route,{method='GET',body,token=admin.token,version}={})=>{
    const response=await fetch(base+'/api'+route,{method,headers:{...(token?{Authorization:`Bearer ${token}`}:{ }),...(body?{'Content-Type':'application/json'}:{}),...(version?{'If-Match':version}:{})},...(body?{body:JSON.stringify(body)}:{})});
    return{status:response.status,data:await response.json()};
  };
  const save=async(kind,item,changes={})=>req(`/admin/cms/${kind}${item.id?`/${item.id}`:''}`,{method:item.id?'PUT':'POST',body:{...item,is_preview:Boolean(item.is_preview),is_featured:Boolean(item.is_featured),...changes},version:item.version});
  let pack,step,item,asset;
  const pathId=Number(run("INSERT INTO learning_paths(slug,title,status) VALUES('cms-path','CMS path','published')").lastInsertRowid);
  await t.test('admin/editor authorization and draft-first course setup',async()=>{
    assert.equal((await req('/admin/cms/snapshot',{token:''})).status,401);
    assert.equal((await req('/admin/cms/snapshot',{token:learner.token})).status,403);
    assert.equal((await req('/admin/cms/snapshot',{token:editor.token})).status,200);
    const draft={path_id:pathId,slug:'cms-course',title:'CMS course',subtitle:'',description:'Course details',deliverable:'MVP',cover_url:'',price_cents:29900,estimated_minutes:60,status:'draft',is_featured:false,sort_order:0};
    assert.equal((await save('packs',{...draft,status:'published'})).status,400);
    assert.equal((await save('packs',{...draft,path_id:99999})).status,400);
    const created=await save('packs',draft);assert.equal(created.status,201);pack=created.data.item;
    assert.equal((await save('packs',draft)).status,409);
    assert.equal(row('SELECT status FROM products WHERE pack_id=?',[pack.id]).status,'inactive');
    step=(await save('steps',{pack_id:pack.id,title:'Chapter one',summary:'Goal',phase:2,status:'draft',sort_order:1})).data.item;
    assert.equal(row('SELECT phase FROM opc_stage_steps WHERE step_id=?',[step.id]).phase,2);
    const d={step_id:step.id,type:'document',title:'Practical document',body:'',resource_url:'',duration_seconds:60,is_preview:false,status:'published',sort_order:1};
    assert.equal((await save('content',d)).status,400);
    assert.equal((await save('content',{...d,body:'Text',resource_url:'javascript:alert(1)'})).status,400);
    assert.equal((await save('content',{...d,resource_url:'/api/materials/99999'})).status,400);
    item=(await save('content',{...d,body:'# Practical document\nDo the work.'})).data.item;
    assert.equal((await save('packs',pack,{status:'published'})).status,400);
    step=(await save('steps',step,{status:'published'})).data.item;
    pack=(await save('packs',pack,{status:'published'})).data.item;
    assert.equal(row('SELECT status FROM products WHERE pack_id=?',[pack.id]).status,'active');
    assert.equal((await req(`/projects/cms-course/content/${item.id}`,{token:learner.token})).status,403);
    assert.equal((await req('/admin/cms/packs/'+pack.id)).data.readiness.ready,true);
  });
  await t.test('stale editor cannot overwrite; archive and restore preserve records',async()=>{
    const original=pack;
    pack=(await save('packs',pack,{title:'Updated course',price_cents:39900})).data.item;
    assert.equal((await save('packs',original,{title:'Stale title'})).status,409);
    assert.equal(row('SELECT title FROM project_packs WHERE id=?',[pack.id]).title,'Updated course');
    assert.equal(row('SELECT price_cents FROM products WHERE pack_id=?',[pack.id]).price_cents,39900);
    pack=(await save('packs',pack,{status:'archived'})).data.item;
    assert.equal((await req('/project-packs/cms-course',{token:''})).status,404);
    assert.equal(row('SELECT status FROM products WHERE pack_id=?',[pack.id]).status,'inactive');
    assert.ok(row('SELECT id FROM content_items WHERE id=?',[item.id]));
    pack=(await save('packs',pack,{status:'published'})).data.item;
    assert.equal((await req('/project-packs/cms-course',{token:''})).status,200);
    assert.ok((await req('/admin/cms/audit')).data.items.length>=7);
  });
  const upload=async(name,token=admin.token)=>{
    const form=new FormData();form.append('file',new Blob(['private course material'],{type:'text/plain'}),name);
    const r=await fetch(base+'/api/admin/cms/assets',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});return{status:r.status,data:await r.json()};
  };
  await t.test('private uploads reject unsafe types and cannot be served as public uploads',async()=>{
    assert.equal((await upload('course.txt',learner.token)).status,403);
    assert.equal((await upload('script.html')).status,400);
    const result=await upload('课程资料.txt');assert.equal(result.status,201);asset=result.data;
    assert.equal(asset.name,'课程资料.txt');
    assert.equal((await fetch(base+asset.url)).status,401);
    const stored=row('SELECT * FROM assets WHERE id=?',[asset.id]);
    assert.equal((await fetch(base+'/uploads/'+stored.filename)).status,404);
    assert.equal((await req('/admin/cms/assets')).data.items[0].private,true);
    const link=(await req(`/admin/cms/assets/${asset.id}/link`)).data.url;
    assert.equal(await (await fetch(base+link)).text(),'private course material');
    assert.equal((await fetch(base+link+'corrupted')).status,401);
    item=(await save('content',item,{type:'download',resource_url:asset.url})).data.item;
    const locked=(await req('/project-packs/cms-course',{token:learner.token})).data;
    assert.equal(JSON.stringify(locked).includes('/api/materials/'),false);
  });
  await t.test('download links recheck entitlement, publication and session revocation',async()=>{
    run("INSERT INTO entitlements(user_id,pack_id,status,starts_at) VALUES(?,?,'active','2000-01-01')",[learner.id,pack.id]);
    const material=(await req(`/projects/cms-course/content/${item.id}`,{token:learner.token})).data.item;
    assert.ok(material.resource_url.includes('?ticket='));
    const url=base+material.resource_url;
    assert.equal((await fetch(url)).status,200);
    run("UPDATE entitlements SET status='revoked' WHERE user_id=?",[learner.id]);
    assert.equal((await fetch(url)).status,403);
    run("UPDATE entitlements SET status='active' WHERE user_id=?",[learner.id]);
    item=(await save('content',item,{status:'archived'})).data.item;
    assert.equal((await fetch(url)).status,403);
    assert.equal((await req(`/projects/cms-course/content/${item.id}`,{token:admin.token})).status,404);
    item=(await save('content',item,{status:'published'})).data.item;
    run('UPDATE users SET token_version=token_version+1 WHERE id=?',[learner.id]);
    assert.equal((await fetch(url)).status,403);
    item=(await save('content',item,{is_preview:true})).data.item;
    const preview=(await req(`/projects/cms-course/content/${item.id}`,{token:''})).data.item.resource_url;
    assert.equal((await fetch(base+preview)).status,200);
    step=(await save('steps',step,{status:'draft'})).data.item;
    assert.equal((await fetch(base+preview)).status,403);
    assert.equal((await req('/project-packs/cms-course',{token:''})).data.steps.length,0);
    assert.equal((await req('/resources',{token:''})).data.items.length,0);
  });
});
