import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {deflateRawSync} from 'node:zlib';
import {createMinerU,markdownFromZip,mineruURL,limitedBody} from '../server/mineru-provider.mjs';
function zip(text,name='full.md'){
 const body=Buffer.from(text),compressed=deflateRawSync(body),filename=Buffer.from(name);let crc=0xffffffff;for(const byte of body){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;
 const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(8,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(body.length,22);local.writeUInt16LE(filename.length,26);
 const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(8,10);central.writeUInt32LE(crc,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(body.length,24);central.writeUInt16LE(filename.length,28);
 const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(46+filename.length,12);end.writeUInt32LE(30+filename.length+compressed.length,16);return Buffer.concat([local,filename,compressed,central,filename,end]);
}
test('MinerU adapter uses official v4 protocol and bounded non-extracting ZIP reader',async t=>{
 await t.test('safe Markdown and UTF-8 are read without writing ZIP entries',()=>assert.equal(markdownFromZip(zip('# 中文课程\n内容')),'# 中文课程\n内容'));
 await t.test('path traversal, absent Markdown, bad CRC and compressed bombs are rejected',()=>{for(const b of [zip('text','../full.md'),zip('text','file.txt'),Buffer.from('bad'),zip('x'.repeat(3*1024*1024))])assert.throws(()=>markdownFromZip(b));const b=zip('text');b[15]^=1;const central=b.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));b[central+16]^=1;assert.throws(()=>markdownFromZip(b));});
 await t.test('HTTPS, credentials, ports and provider host allowlist are enforced',()=>{for(const url of ['http://mineru.oss-cn-shanghai.aliyuncs.com/a','https://127.0.0.1/a','https://evil.invalid/a','https://mineru.oss-cn-shanghai.aliyuncs.com:444/a','https://user:pass@mineru.oss-cn-shanghai.aliyuncs.com/a'])assert.throws(()=>mineruURL(url,'upload'));});
 await t.test('missing key is genuinely unavailable',()=>assert.equal(createMinerU({key:''}),null));
 await t.test('oversized provider bodies stop reading',async()=>assert.rejects(()=>limitedBody(new Response('123456'),3)));
 await t.test('official submit/query transport preserves file identity and never sends API key to result CDN',async()=>{
  const calls=[],id=randomUUID(),provider=createMinerU({key:'isolated-key',resolve:async()=>[{address:'8.8.8.8'}],fetcher:async(url,options)=>{calls.push({url,options});if(url.endsWith('file-urls/batch'))return Response.json({code:0,data:{batch_id:'batch-1',file_urls:['https://mineru.oss-cn-shanghai.aliyuncs.com/api-upload/file']}});if(url.includes('extract-results'))return Response.json({code:0,data:{extract_result:[{data_id:id,state:'done',full_zip_url:'https://cdn-mineru.openxlab.org.cn/result.zip'}]}});return new Response(zip('# 教学资料'));}});
  const submitted=await provider.submit('课件.pptx',id);assert.equal(submitted.batchId,'batch-1');assert.equal(JSON.parse(calls[0].options.body).model_version,'vlm');assert.equal((await provider.poll('batch-1',id)).body,'# 教学资料');assert.equal(calls.at(-1).options.headers,undefined);assert.equal(calls.at(-1).options.redirect,'error');
 });
 await t.test('private DNS and mismatched result identity cannot fetch archives',async()=>{
  const id=randomUUID(),provider=createMinerU({key:'isolated-key',resolve:async()=>[{address:'127.0.0.1'}],fetcher:async()=>Response.json({code:0,data:{extract_result:[{data_id:id,state:'done',full_zip_url:'https://cdn-mineru.openxlab.org.cn/result.zip'}]}})});await assert.rejects(()=>provider.poll('batch-1',id));await assert.rejects(()=>provider.poll('batch-1','other-file'));
 });
});
test('commercial completion: analytics, bundle, parsing and automatic private certificates',async t=>{
 const dir=mkdtempSync(path.join(tmpdir(),'osl-commercial-'));
 Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:path.join(dir,'isolated.db'),UPLOAD_DIR:path.join(dir,'uploads'),JWT_SECRET:'isolated-commercial-test',ASSET_STORAGE:'local',AI_ENABLED:'false',MINERU_API_KEY:''});
 const {db,row,run,applyMigrations}=await import('../server/db.mjs'),{createApp}=await import('../server/index.mjs'),{signUser}=await import('../server/auth.mjs');
 const {courseCurriculum,issueCourseCertificate,reconcileCertificates}=await import('../server/course-certificates.mjs');
 const {projectAccess}=await import('../server/learning-model.mjs');
 const add=(sql,args=[])=>Number(run(sql,args).lastInsertRowid),user=(name,role='learner')=>{const id=add('INSERT INTO users(email,password_hash,name,role,email_verified) VALUES(?,?,?,?,1)',[name+'@example.invalid','unused',name,role]);const u=row('SELECT * FROM users WHERE id=?',[id]);return {...u,token:signUser(u)};};
 const admin=user('owner','admin'),editor=user('editor','editor'),learner=user('learner'),other=user('other');
 const lp=add("INSERT INTO learning_paths(slug,title,status) VALUES('commercial','课程路径','published')"),pack=add("INSERT INTO project_packs(path_id,slug,title,status) VALUES(?,'commercial','正式课程','published')",[lp]),chapter=add("INSERT INTO project_steps(pack_id,title,status) VALUES(?,'章节','published')",[pack]);
 const config={isDemoMedia:false,videoAssetId:null,pptAssetId:null,subtitleAssetId:null,durationSeconds:120,slides:[{id:'formal-slide',text:'正式课程教学文字',assetId:null}],mappings:[],tasks:[],operations:[],relatedPlacementIds:[]};
 const lesson=()=>{const id=add("INSERT INTO learning_lessons(title,config,status) VALUES('正式课时',?,'published')",[JSON.stringify(config)]);return add("INSERT INTO lesson_placements(lesson_id,chapter_id,status) VALUES(?,?,'published')",[id,chapter]);},p1=lesson(),p2=lesson();
 run("INSERT INTO entitlements(user_id,pack_id,status) VALUES(?,?,'active')",[learner.id,pack]);
 const project=add("INSERT INTO practice_projects(slug,title,status) VALUES('commercial','付费项目','published')");run("INSERT INTO practice_project_settings(project_id,access_type) VALUES(?,'paid')",[project]);
 let calls=0,failPoll=false,failSubmit=false;
 const provider={async submit(_name,id){calls++;if(failSubmit)throw Error('secret-url-and-provider-body');return {batchId:'batch-'+id,uploadUrl:'https://mineru.oss-cn-shanghai.aliyuncs.com/upload'};},async upload(_url,stream){for await(const _ of stream){}},async poll(){calls++;if(failPoll)throw Error('SECRET');return {state:'review',body:'# 解析课程\n人工审核的教学文字'};}};
 const app=createApp({mineruProvider:provider}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{await new Promise(r=>server.close(r));db.close();rmSync(dir,{recursive:true,force:true});});
 const base='http://127.0.0.1:'+server.address().port;
 const request=async(url,u=admin,method='GET',body,version)=>{const r=await fetch(base+'/api'+url,{method,headers:{...(u?{Authorization:'Bearer '+u.token}:{}),...(body?{'Content-Type':'application/json'}:{}),...(version!==undefined?{'If-Match':String(version)}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json().catch(()=>null)};};
 const progress=async(id,u=learner,complete=true)=>{const v=row('SELECT version FROM learning_progress WHERE user_id=? AND placement_id=?',[u.id,id])?.version||0;return request('/learning/placements/'+id+'/progress',u,'PUT',{video_time:120,video_duration:120,slide_id:null,follow_video:true,tasks:[],complete},v);};
 await t.test('additive migrations repeat without seeding or modifying existing business rows',()=>{const before=JSON.stringify(db.prepare('SELECT * FROM users').all());applyMigrations();applyMigrations();assert.equal(JSON.stringify(db.prepare('SELECT * FROM users').all()),before);assert.equal(row('SELECT COUNT(*) n FROM course_certificates').n,0);assert.equal(row('PRAGMA quick_check').quick_check,'ok');assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);});
 await t.test('admin operations are owner-only; anonymous and editors cannot read or write',async()=>{for(const url of ['/admin/readiness','/admin/analytics','/admin/parsing','/admin/certificates','/admin/commercial/settings']){assert.equal((await request(url,null)).status,401);assert.equal((await request(url,editor)).status,403);assert.equal((await request(url,learner)).status,403);assert.equal((await request(url)).status,200);}});
 await t.test('readiness reports configured but paused services without contacting providers or changing records',async()=>{
  const tables=['document_parse_jobs','course_certificates','certificate_policies','telemetry_events','commercial_settings','completion_receipts'];
  const snapshot=()=>JSON.stringify(tables.map(table=>db.prepare('SELECT * FROM '+table).all()));
  const before=snapshot(),d=(await request('/admin/readiness')).data;
  assert.deepEqual(d.capabilities.parser,{configured:true,enabled:false,jobs:0});assert.deepEqual(d.capabilities.telemetry,{enabled:false,events:0});
  assert.equal(d.capabilities.certificates.issued,0);assert.equal(d.capabilities.certificates.courses[0].total,2);assert.equal(d.capabilities.certificates.courses[0].empty,0);assert.equal(d.capabilities.certificates.courses[0].enabled,0);
  assert.equal(d.items[0].hasSubtitle,false);assert.equal(d.items[0].demo,false);assert.equal(calls,0);assert.equal(snapshot(),before);assert.ok(!d.limitations.some(s=>s.includes('PPT/PDF 解析未接入')));
 });
 await t.test('read-only admin queries do not contact providers or grant certificates',async()=>{assert.equal(calls,0);assert.equal(row('SELECT COUNT(*) n FROM document_parse_jobs').n,0);assert.equal(row('SELECT COUNT(*) n FROM course_certificates').n,0);});
 await t.test('AI allowance reads the enforced account budget privately without consuming or exposing another account',async()=>{
  const {rateLimit,rateLimitStatus}=await import('../server/account-security.mjs');
  assert.equal((await request('/learning/ai/allowance',null)).status,401);
  assert.equal((await request('/learning/ai/allowance',learner)).data.daily.remaining,30);
  rateLimit('learning-ai-day',String(learner.id),30,86400);for(let i=0;i<3;i++)rateLimit('learning-ai-day',String(other.id),30,86400);
  const before=JSON.stringify(db.prepare('SELECT * FROM auth_rate_limits ORDER BY key').all()),d=(await request('/learning/ai/allowance?userId='+other.id,learner)).data;
  assert.deepEqual(Object.keys(d).sort(),['available','busy','daily','minute']);assert.deepEqual(Object.keys(d.daily).sort(),['limit','remaining','resetAt']);
  assert.equal(d.daily.remaining,29);assert.equal(d.minute.remaining,10);assert.ok(d.daily.resetAt);assert.equal((await request('/learning/ai/allowance',other)).data.daily.remaining,27);
  assert.equal(JSON.stringify(db.prepare('SELECT * FROM auth_rate_limits ORDER BY key').all()),before);
  assert.deepEqual(rateLimitStatus('learning-ai-day',String(learner.id),30,Date.now()+86401000),{limit:30,remaining:30,resetAt:null});
 });
 await t.test('failed model calls consume the same allowance shown to the learner, not just successful usage records',async()=>{
  const {courseAIService}=await import('../server/course-ai-service.mjs');
  const before=(await request('/learning/ai/allowance',learner)).data.daily.remaining;
  courseAIService.configure({generate:async()=>{throw Object.assign(new Error('isolated model failure'),{status:502});}});
  try{assert.equal((await request('/learning/ai/tutor',learner,'POST',{question:'隔离通用问题',mode:'general'})).status,502);assert.equal((await request('/learning/ai/allowance',learner)).data.daily.remaining,before-1);}finally{courseAIService.configure(undefined);}
 });
 await t.test('telemetry is disabled initially and accepts no data while paused',async()=>{assert.equal((await request('/telemetry/config',null)).data.enabled,false);assert.equal((await request('/telemetry/events',null,'POST',{items:[{bad:'private'}]})).status,204);assert.equal(row('SELECT COUNT(*) n FROM telemetry_events').n,0);});
 await t.test('versioned switches reject stale writes and invalid inputs',async()=>{assert.equal((await request('/admin/commercial/settings',admin,'PUT',{telemetry_enabled:true,parser_enabled:true},0)).status,200);assert.equal((await request('/admin/commercial/settings',admin,'PUT',{telemetry_enabled:false,parser_enabled:false},0)).status,409);assert.equal((await request('/admin/commercial/settings',admin,'PUT',{telemetry_enabled:true,parser_enabled:true,secret:'x'},1)).status,400);});
 const event={id:randomUUID(),session:randomUUID(),kind:'view',route:'/learn/secret-course/lessons/1?token=PRIVATE#secret'};
 await t.test('events canonicalize paths, deduplicate IDs and never store private search/token data',async()=>{for(let n=0;n<2;n++)assert.equal((await request('/telemetry/events',null,'POST',{items:[event]})).status,204);const stored=row('SELECT * FROM telemetry_events');assert.equal(stored.route,'lesson');assert.equal(row('SELECT COUNT(*) n FROM telemetry_events').n,1);assert.equal(JSON.stringify(stored).includes('PRIVATE'),false);});
 await t.test('arbitrary fields, paths, non-finite metrics and forged payment events are rejected',async()=>{for(const e of [{...event,question:'private'},{...event,route:'/admin/orders'},{...event,kind:'paid'},{...event,kind:'performance',metric:'LCP',value:-1},{...event,kind:'performance',metric:'CLS',value:101}])assert.equal((await request('/telemetry/events',null,'POST',{items:[e]})).status,400);});
 await t.test('cohort conversion uses actual ordered server payments and not browser claims',async()=>{run("INSERT INTO orders(order_no,user_id,status,amount_cents,paid_at) VALUES('TEST-VERIFIED',?,'paid',49900,CURRENT_TIMESTAMP)",[learner.id]);await progress(p1,learner,false);const d=(await request('/admin/analytics?days=7')).data;assert.equal(d.cohort.registered,2);assert.equal(d.cohort.checkout,1);assert.equal(d.cohort.paid,1);assert.equal(d.cohort.learned,1);assert.equal(d.cohort.paidRate,.5);assert.equal(d.financial.grossCents,49900);assert.equal((await request('/admin/analytics?days=100')).status,400);});
 await t.test('performance p75 uses independent-page samples',async()=>{for(const value of [10,20,30,40])await request('/telemetry/events',null,'POST',{items:[{...event,id:randomUUID(),session:randomUUID(),kind:'performance',metric:'LCP',value}]});const d=(await request('/admin/analytics')).data;assert.equal(d.performance[0].samples,4);assert.equal(d.performance[0].p75,30);});
 await t.test('course grant includes paid projects only when attached to complete-course offer',async()=>{assert.equal(projectAccess(learner,project),false);const product=add("INSERT INTO products(pack_id,sku,title,price_cents,status) VALUES(?,'commercial','完整课程',49900,'active')",[pack]);const {paymentConfiguration,savePaymentConfig}=await import('../server/payment-configuration.mjs');savePaymentConfig(admin,0,{settings:{...paymentConfiguration().settings,productId:product,priceCents:49900,originalPriceCents:99900},secrets:{}});assert.equal(projectAccess(learner,project),true);assert.equal(projectAccess(other,project),false);run("UPDATE entitlements SET status='revoked' WHERE user_id=?",[learner.id]);assert.equal(projectAccess(learner,project),false);run("INSERT INTO project_entitlements(user_id,project_id,status) VALUES(?,?,'active')",[learner.id,project]);assert.equal(projectAccess(learner,project),true);run("UPDATE entitlements SET status='active' WHERE user_id=?",[learner.id]);});
 await t.test('standalone new project orders are blocked without touching historical orders',async()=>{const id=add("INSERT INTO products(project_id,sku,title,price_cents,status) VALUES(?,'project','项目',10000,'active')",[project]),count=row('SELECT COUNT(*) n FROM orders').n;assert.equal((await request('/orders',learner,'POST',{productId:id})).status,409);assert.equal(row('SELECT COUNT(*) n FROM orders').n,count);});
 await t.test('no certificate without explicit full-curriculum policy',async()=>{assert.equal((await progress(p1)).status,200);assert.equal(issueCourseCertificate(learner,pack),null);assert.equal(row('SELECT COUNT(*) n FROM course_certificates').n,0);});
await t.test('expected full count, teaching-content and no-demo checks prevent partial-course issuance',async()=>{assert.equal((await request('/admin/certificates/courses/'+pack,admin,'PUT',{enabled:true,expectedLessons:40},0)).status,409);run("UPDATE learning_lessons SET config=? WHERE id=(SELECT lesson_id FROM lesson_placements WHERE id=?)",[JSON.stringify({...config,isDemoMedia:true}),p2]);assert.equal((await request('/admin/certificates/courses/'+pack,admin,'PUT',{enabled:true,expectedLessons:2},0)).status,409);assert.equal((await progress(p2)).status,409);run("UPDATE learning_lessons SET config=? WHERE id=(SELECT lesson_id FROM lesson_placements WHERE id=?)",[JSON.stringify({...config,slides:[]}),p2]);assert.equal((await request('/admin/certificates/courses/'+pack,admin,'PUT',{enabled:true,expectedLessons:2},0)).status,409);run("UPDATE learning_lessons SET config=? WHERE id=(SELECT lesson_id FROM lesson_placements WHERE id=?)",[JSON.stringify(config),p2]);});
 await t.test('enabling exact formal curriculum issues only after last completed placement',async()=>{assert.equal(courseCurriculum(pack).length,2);assert.equal((await request('/admin/certificates/courses/'+pack,admin,'PUT',{enabled:true,expectedLessons:2},0)).status,200);assert.equal(issueCourseCertificate(learner,pack),null);const d=await progress(p2);assert.equal(d.status,200);assert.ok(d.data.certificate.id);assert.equal(row('SELECT COUNT(*) n FROM course_certificates').n,1);});
 const cert=()=>row('SELECT * FROM course_certificates WHERE user_id=?',[learner.id]);
 await t.test('repeat progress and background checks issue exactly one certificate',async()=>{const id=cert().id;await progress(p2);reconcileCertificates();assert.equal(cert().id,id);assert.equal(row('SELECT COUNT(*) n FROM course_certificates').n,1);});
 await t.test('private certificate lists and documents require current owner auth',async()=>{const url='/me/certificates/'+cert().id+'/document';assert.equal((await request(url,other)).status,404);assert.equal((await request(url,null)).status,401);assert.equal((await request('/me/certificates',other)).data.items.length,0);const d=await request(url,learner);assert.equal(d.status,200);assert.ok(d.data.html.includes('正式课程'));assert.ok(!d.data.html.includes(learner.email));});
 await t.test('certificate HTML escapes recipient input and snapshots issued identity',async()=>{const {certificateHTML}=await import('../server/course-certificates.mjs');assert.ok(certificateHTML({...cert(),recipient:'<img src=x onerror=alert(1)>'}).includes('&lt;img'));run("UPDATE users SET name='新昵称' WHERE id=?",[learner.id]);assert.equal(cert().recipient,'learner');});
 await t.test('certificate notifications are private and link to learner outcomes',async()=>{assert.ok((await request('/notifications',learner)).data.items.some(i=>i.key==='certificate:'+cert().id));assert.ok(!(await request('/notifications',other)).data.items.some(i=>i.key==='certificate:'+cert().id));});
 await t.test('revoked course entitlement blocks certificate downloads; independent project grant survives',async()=>{run("UPDATE entitlements SET status='revoked' WHERE user_id=?",[learner.id]);assert.equal((await request('/me/certificates/'+cert().id+'/document',learner)).status,403);assert.equal(projectAccess(learner,project),true);run("UPDATE entitlements SET status='active' WHERE user_id=?",[learner.id]);});
 await t.test('directory revisions pause new issuance and completion receipts are not retroactively trusted',async()=>{run("INSERT INTO entitlements(user_id,pack_id,status) VALUES(?,?,'active')",[other.id,pack]);run('UPDATE learning_lessons SET version=version+1 WHERE id=(SELECT lesson_id FROM lesson_placements WHERE id=?)',[p1]);await progress(p1,other);await progress(p2,other);assert.equal(issueCourseCertificate(other,pack),null);assert.equal((await request('/admin/certificates/courses/'+pack,admin,'PUT',{enabled:true,expectedLessons:2},1)).status,200);reconcileCertificates();assert.ok(row('SELECT id FROM course_certificates WHERE user_id=?',[other.id]));});
 await t.test('revocation requires owner and reason, is idempotent and never auto-reissues',async()=>{assert.equal((await request('/admin/certificates/'+cert().id+'/revoke',editor,'POST',{reason:'test'})).status,403);assert.equal((await request('/admin/certificates/'+cert().id+'/revoke',admin,'POST',{reason:''})).status,400);for(let n=0;n<2;n++)assert.equal((await request('/admin/certificates/'+cert().id+'/revoke',admin,'POST',{reason:'隔离撤销测试'})).status,200);await progress(p2);reconcileCertificates();assert.ok(cert().revoked_at);assert.equal((await request('/me/certificates/'+cert().id+'/document',learner)).status,403);});
 mkdirSync(path.join(dir,'uploads-private'));const file=Buffer.from('%PDF-1.4 isolated fixture'),asset=add("INSERT INTO assets(filename,original_name,mime_type,size_bytes,url,uploaded_by) VALUES('isolated.pdf','隔离课件.pdf','application/pdf',?,'',?)",[file.length,admin.id]);run('UPDATE assets SET url=? WHERE id=?',['/api/materials/'+asset,asset]);writeFileSync(path.join(dir,'uploads-private','isolated.pdf'),file);
 let job;
 await t.test('parsing requires explicit transfer consent and authorized document formats',async()=>{const before=calls;assert.equal((await request('/admin/parsing',admin,'POST',{assetId:asset,consent:false})).status,400);const movie=add("INSERT INTO assets(filename,original_name,mime_type,size_bytes,url) VALUES('movie.mp4','movie.mp4','video/mp4',20,'')");run('UPDATE assets SET url=? WHERE id=?',['/api/materials/'+movie,movie]);assert.equal((await request('/admin/parsing',admin,'POST',{assetId:movie,consent:true})).status,400);assert.equal(calls,before);});
 await t.test('one durable task per asset prevents duplicate submissions',async()=>{const r=await request('/admin/parsing',admin,'POST',{assetId:asset,consent:true});assert.equal(r.status,202);job=r.data;assert.equal(job.state,'running');assert.equal(JSON.stringify(job).includes('uploadUrl'),false);assert.equal((await request('/admin/parsing',admin,'POST',{assetId:asset,consent:true})).status,409);});
 await t.test('transient polling errors preserve job and sanitize upstream errors',async()=>{failPoll=true;assert.equal((await request('/admin/parsing/'+job.id+'/check',admin,'POST')).status,502);assert.equal(row('SELECT state FROM document_parse_jobs WHERE id=?',[job.id]).state,'running');assert.equal((await request('/admin/parsing/'+job.id)).data.error.includes('SECRET'),false);failPoll=false;run('UPDATE document_parse_jobs SET checked_at=NULL WHERE id=?',[job.id]);});
 await t.test('successful parsing awaits review; no published content is overwritten',async()=>{assert.equal((await request('/admin/parsing/'+job.id+'/check',admin,'POST')).status,200);const d=(await request('/admin/parsing/'+job.id)).data;assert.equal(d.state,'review');assert.ok(d.body.includes('解析课程'));assert.equal(row('SELECT COUNT(*) n FROM content_library').n,0);});
 await t.test('CAS-protected review creates a draft with provenance, not a published lesson',async()=>{const d=(await request('/admin/parsing/'+job.id)).data;assert.equal((await request('/admin/parsing/'+job.id+'/import',admin,'POST',{title:'审核资料',body:d.body},0)).status,409);const r=await request('/admin/parsing/'+job.id+'/import',admin,'POST',{title:'审核资料',body:d.body},d.version);assert.equal(r.status,201);assert.equal(row('SELECT status FROM content_library WHERE id=?',[r.data.libraryId]).status,'draft');assert.equal(row('SELECT library_id FROM document_parse_jobs WHERE id=?',[job.id]).library_id,r.data.libraryId);assert.equal((await request('/admin/parsing/'+job.id+'/import',admin,'POST',{title:'重复资料',body:d.body},d.version)).status,409);assert.equal(row('SELECT COUNT(*) n FROM lesson_materials').n,0);});
 await t.test('ambiguous submit persists uncertain state and never auto-resubmits',async()=>{failSubmit=true;const r=await request('/admin/parsing',admin,'POST',{assetId:asset,consent:true});assert.equal(r.status,502);const uncertain=row('SELECT * FROM document_parse_jobs WHERE id=?',[r.data.id]);assert.equal(uncertain.state,'uncertain');const n=calls;await app.locals.pollDocumentParsing();assert.equal(calls,n);assert.equal((await request('/admin/parsing/'+uncertain.id+'/check',admin,'POST')).status,409);assert.equal((await request('/admin/parsing/'+uncertain.id+'/close',admin,'POST',{confirm:true},0)).status,409);assert.equal((await request('/admin/parsing/'+uncertain.id+'/close',admin,'POST',{confirm:true},uncertain.version)).status,200);failSubmit=false;});
 await t.test('integrity and original course records remain valid after all isolated workflows',()=>{assert.equal(row('PRAGMA quick_check').quick_check,'ok');assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);assert.equal(row('SELECT COUNT(*) n FROM lesson_placements').n,2);assert.equal(row('SELECT COUNT(*) n FROM orders').n,1);});
});
