import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {COMMUNITY_SETTINGS,EMPTY_ARTICLE} from '../server/community-definition.mjs';

test('official community publishing and membership boundaries',async t=>{
  const dir=mkdtempSync(path.join(tmpdir(),'oneshowlearn-community-'));
  Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:path.join(dir,'test.db'),UPLOAD_DIR:path.join(dir,'uploads'),JWT_SECRET:'community-test-only'});
  const {db,row,run}=await import('../server/db.mjs');const {signUser}=await import('../server/auth.mjs');const {createApp}=await import('../server/index.mjs');
  const server=createApp().listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  t.after(async()=>{await new Promise(r=>server.close(r));db.close();rmSync(dir,{recursive:true,force:true});});
  const user=(name,role)=>{const id=Number(run('INSERT INTO users(email,password_hash,name,role,email_verified) VALUES(?,?,?,?,1)',[`${name}@example.com`,'unused',name,role]).lastInsertRowid);return {id,token:signUser(row('SELECT * FROM users WHERE id=?',[id]))};};
  const admin=user('admin','admin'),editor=user('editor','editor'),learner=user('learner','learner');
  const request=async(url,{method='GET',body,version,token=admin.token}={})=>{const res=await fetch(`http://127.0.0.1:${server.address().port}/api${url}`,{method,headers:{...(token?{Authorization:`Bearer ${token}`}:{ }),...(body?{'Content-Type':'application/json'}:{}),...(version!==undefined?{'If-Match':String(version)}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,data:await res.json()};};
  let article,config;
  const act=(item,action,extra={})=>request(`/admin/community/${item.id}/${action}`,{method:'POST',version:item.version,...extra});
  const save=(item,draft)=>request(`/admin/community/${item.id}`,{method:'PUT',version:item.version,body:{draft}});
  await t.test('empty feed and auth guards never expose drafts',async()=>{
    assert.equal((await request('/community',{token:''})).status,401);
    for(const token of ['',learner.token])assert.equal((await request('/admin/community',{token})).status,token?403:401);
    assert.deepEqual((await request('/community',{token:learner.token})).data.items,[]);
    const result=await request('/admin/community',{method:'POST',token:editor.token,body:{kind:'article',draft:{...EMPTY_ARTICLE,title:'Official course guide',summary:'A guide',body:'VISIBLE VERSION',topic:'入门'}}});assert.equal(result.status,201);article=result.data.item;
    assert.equal((await request('/community/articles/'+article.id,{token:learner.token})).status,404);
    assert.equal((await act(article,'publish',{token:learner.token})).status,403);
  });
  await t.test('explicit publish, draft isolation, stale protection and recoverable history',async()=>{
    article=(await act(article,'publish')).data.item;
    assert.equal((await request('/community/articles/'+article.id,{token:learner.token})).data.item.body,'VISIBLE VERSION');
    const old=article;article=(await save(article,{...article.draft,title:'New draft title',body:'PRIVATE DRAFT'})).data.item;
    assert.equal((await save(old,{...old.draft,body:'stale'})).status,409);
    assert.equal((await act(old,'publish')).status,409);
    assert.equal((await request('/community/articles/'+article.id,{token:learner.token})).data.item.body,'VISIBLE VERSION');
    const feed=(await request('/community',{token:learner.token})).data;assert.ok(!JSON.stringify(feed).includes('PRIVATE DRAFT'));assert.ok(!Object.hasOwn(feed.items[0],'body'));
    article=(await act(article,'publish')).data.item;
    assert.equal((await request(`/admin/community/${article.id}/history`)).data.items.length,2);
    article=(await act(article,'archive')).data.item;
    assert.equal((await request('/community/articles/'+article.id)).status,404);
    assert.equal((await request('/community')).data.items.length,0);
    article=(await act(article,'restore')).data.item;assert.equal((await request('/community')).data.items.length,1);
    assert.equal((await request(`/admin/community/${article.id}/history`,{token:learner.token})).status,403);
  });
  await t.test('membership QR remains private and draft settings cannot leak',async()=>{
    const draft={...COMMUNITY_SETTINGS,groupEnabled:true,qrUrl:'https://example.com/member-qr.png'};
    config=(await request('/admin/community',{method:'POST',body:{kind:'settings',draft}})).data.item;
    assert.equal((await request('/community')).data.settings.qrUrl,'');
    config=(await act(config,'publish')).data.item;
    assert.equal((await request('/community',{token:learner.token})).data.settings.qrUrl,'');
    assert.equal((await request('/community',{token:learner.token})).data.settings.groupReady,true);
    assert.equal((await request('/community')).data.settings.qrUrl,draft.qrUrl);
    const pathId=Number(run("INSERT INTO learning_paths(slug,title,status) VALUES('community-test','Test','published')").lastInsertRowid);
    const pack=Number(run("INSERT INTO project_packs(path_id,slug,title,status) VALUES(?,'community-test','Test','published')",[pathId]).lastInsertRowid);
    const ent=Number(run("INSERT INTO entitlements(user_id,pack_id,status,starts_at) VALUES(?,?,'active','2000-01-01')",[learner.id,pack]).lastInsertRowid);
    assert.equal((await request('/community',{token:learner.token})).data.settings.qrUrl,draft.qrUrl);
    run("UPDATE entitlements SET expires_at='2001-01-01' WHERE id=?",[ent]);
    assert.equal((await request('/community',{token:learner.token})).data.settings.qrUrl,'');
    config=(await save(config,{...draft,groupAudience:'signed-in'})).data.item;
    assert.equal((await request('/community',{token:learner.token})).data.settings.qrUrl,'');
    config=(await act(config,'publish')).data.item;
    assert.equal((await request('/community',{token:learner.token})).data.settings.qrUrl,draft.qrUrl);
    assert.equal((await save(config,{...draft,qrUrl:'javascript:alert(1)'})).status,400);
    config=(await save(config,{...draft,qrUrl:''})).data.item;
    assert.equal((await act(config,'publish')).status,400);
  });
  await t.test('recommended sources retain publication and paid-content boundaries',async()=>{
    const pack=row("SELECT id FROM project_packs WHERE slug='community-test'").id;
    const step=Number(run("INSERT INTO project_steps(pack_id,title,status) VALUES(?,'Chapter','published')",[pack]).lastInsertRowid);
    const id=Number(run("INSERT INTO content_items(step_id,title,type,body,status) VALUES(?,'Paid source','document','PAID_SECRET','published')",[step]).lastInsertRowid);
    config=(await save(config,{...COMMUNITY_SETTINGS,resourceIds:[id]})).data.item;config=(await act(config,'publish')).data.item;
    const feed=(await request('/community',{token:learner.token})).data;assert.equal(feed.resources.length,1);assert.ok(!JSON.stringify(feed).includes('PAID_SECRET'));
    assert.equal((await request(`/projects/community-test/content/${id}`,{token:learner.token})).status,403);
    run("UPDATE content_items SET status='draft' WHERE id=?",[id]);assert.deepEqual((await request('/community')).data.resources,[]);
  });
  await t.test('uploaded QR and covers stay private until publication and revoke live',async()=>{
    const root=`http://127.0.0.1:${server.address().port}`;
    const {materialUrl}=await import('../server/materials.mjs');
    const learnerUser=row('SELECT * FROM users WHERE id=?',[learner.id]);
    const upload=async(bytes,name='qr.png',mime='image/png',token=admin.token)=>{
      const form=new FormData();form.append('file',new Blob([bytes],{type:mime}),name);
      const res=await fetch(root+'/api/admin/cms/assets',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});return {status:res.status,data:await res.json()};
    };
    const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jE5kAAAAASUVORK5CYII=','base64');
    assert.equal((await upload(png,'qr.png','image/png',learner.token)).status,403);
    const qr=await upload(png);assert.equal(qr.status,201);
    assert.equal((await fetch(root+qr.data.url)).status,401);
    const qrTicket=materialUrl(qr.data.url,learnerUser);
    assert.equal((await fetch(root+qrTicket)).status,403);
    config=(await save(config,{...COMMUNITY_SETTINGS,qrUrl:qr.data.url,groupEnabled:true,groupAudience:'signed-in',groupExpiresAt:'2099-12-31',groupInstructions:'请备注学习账号后入群'})).data.item;
    assert.ok(config);
    assert.equal((await fetch(root+qrTicket)).status,403);
    config=(await act(config,'publish')).data.item;
    const settings=(await request('/community',{token:learner.token})).data.settings;
    assert.match(settings.qrUrl,/^\/api\/materials\/\d+\?ticket=/);
    assert.equal(settings.groupInstructions,'请备注学习账号后入群');
    const response=await fetch(root+settings.qrUrl);assert.equal(response.status,200);assert.deepEqual(Buffer.from(await response.arrayBuffer()),png);
    config=(await save(config,{...config.draft,groupExpiresAt:'2000-01-01'})).data.item;config=(await act(config,'publish')).data.item;
    const expired=(await request('/community',{token:learner.token})).data.settings;
    assert.equal(expired.groupExpired,true);assert.equal(expired.qrUrl,'');assert.equal((await fetch(root+settings.qrUrl)).status,403);
    config=(await save(config,{...config.draft,groupExpiresAt:'2099-12-31',groupAudience:'entitled'})).data.item;config=(await act(config,'publish')).data.item;
    assert.equal((await fetch(root+qrTicket)).status,403);
    run("UPDATE entitlements SET expires_at=NULL WHERE user_id=?",[learner.id]);
    assert.equal((await fetch(root+qrTicket)).status,200);
    run("UPDATE entitlements SET status='revoked' WHERE user_id=?",[learner.id]);
    assert.equal((await fetch(root+qrTicket)).status,403);
    config=(await save(config,{...config.draft,groupAudience:'signed-in'})).data.item;config=(await act(config,'publish')).data.item;
    config=(await act(config,'archive')).data.item;assert.equal((await fetch(root+qrTicket)).status,403);
    const cover=await upload(png,'cover.png');const coverTicket=materialUrl(cover.data.url,learnerUser);
    article=(await save(article,{...article.draft,coverUrl:cover.data.url})).data.item;
    assert.equal((await fetch(root+coverTicket)).status,403);
    article=(await act(article,'publish')).data.item;assert.equal((await fetch(root+coverTicket)).status,200);
    article=(await save(article,{...article.draft,coverUrl:''})).data.item;article=(await act(article,'publish')).data.item;
    assert.equal((await fetch(root+coverTicket)).status,403);
    const invalid=await upload(Buffer.from('<svg onload="alert(1)"></svg>'));
    assert.equal((await save(article,{...article.draft,coverUrl:invalid.data.url})).status,400);
    assert.equal((await save(article,{...article.draft,coverUrl:'/api/materials/99999999'})).status,400);
    assert.equal((await save(config,{...config.draft,groupExpiresAt:'2026-02-31'})).status,400);
  });
});
