import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { emptyProduct, phaseProgress, safeResourceUrl } from '../src/opc-model.js';

test('OPC progress and links are honest and safe', () => {
  assert.deepEqual(phaseProgress([]), { completed:0, total:0, percent:0 });
  assert.equal(phaseProgress([{progress:'completed'}, {progress:'started'}, {}]).percent,33);
  for (const url of ['javascript:alert(1)', 'data:text/html,x', '//evil.example', '/uploads/../../secret', 'https://user:pass@example.com']) assert.equal(safeResourceUrl(url),'');
  assert.equal(safeResourceUrl('/uploads/guide.pdf'),'/uploads/guide.pdf');
  assert.equal(safeResourceUrl('https://example.com/guide'),'https://example.com/guide');
});

test('OPC CMS, course access and personal product persistence', async t => {
  const temp=mkdtempSync(path.join(tmpdir(),'oneshowlearn-opc-test-'));
  Object.assign(process.env,{ NODE_ENV:'test', DATABASE_PATH:path.join(temp,'test.db'), UPLOAD_DIR:path.join(temp,'uploads'), JWT_SECRET:'opc-tests-only' });
  const {db,row,run}=await import('../server/db.mjs');
  const {signUser}=await import('../server/auth.mjs');
  const {createApp}=await import('../server/index.mjs');
  const server=createApp().listen(0,'127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  t.after(async()=>{ await new Promise(resolve=>server.close(resolve)); db.close(); rmSync(temp,{recursive:true,force:true}); });
  const base=`http://127.0.0.1:${server.address().port}/api`;
  const req=async(route,token,body,headers={})=>{ const res=await fetch(base+route,{method:body===undefined?'GET':'PUT',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} : {}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}); return {status:res.status,data:await res.json(),cache:res.headers.get('cache-control')}; };
  const user=(name,role='learner')=>{const id=Number(run("INSERT INTO users(email,password_hash,name,role,email_verified) VALUES(?,?,?,?,1)",[`${name}@example.com`,'unused',name,role]).lastInsertRowid); return {id,token:signUser(row('SELECT * FROM users WHERE id=?',[id]))};};
  const admin=user('owner','admin'), learner=user('student'), other=user('other');
  const pathId=Number(run("INSERT INTO learning_paths(slug,title,status) VALUES('opc','OPC','published')").lastInsertRowid);
  const packId=Number(run("INSERT INTO project_packs(path_id,slug,title,status) VALUES(?,'opc-test','OPC Course','published')",[pathId]).lastInsertRowid);
  const stepId=Number(run("INSERT INTO project_steps(pack_id,title,status) VALUES(?,'Chapter','published')",[packId]).lastInsertRowid);
  const item=(status,preview=0)=>Number(run("INSERT INTO content_items(step_id,type,title,body,resource_url,status,is_preview) VALUES(?,'document','Lesson','PRIVATE_BODY','https://example.com/private',?,?)",[stepId,status,preview]).lastInsertRowid);
  const paid=item('published'), preview=item('published',1), draft=item('draft');
  await t.test('phase assignment is admin-only, validated and explicit',async()=>{
    assert.equal((await req('/opc/curriculum')).data.phases[1].items.length,0);
    assert.equal((await req(`/admin/opc/steps/${stepId}`,learner.token,{phase:2})).status,403);
    assert.equal((await req(`/admin/opc/steps/${stepId}`,admin.token,{phase:6})).status,400);
    assert.equal((await req(`/admin/opc/steps/9999`,admin.token,{phase:2})).status,404);
    assert.equal((await req(`/admin/opc/steps/${stepId}`,admin.token,{phase:2})).status,200);
    const chapter={packId,title:'可编辑章节',summary:'后台可修改发布状态',sortOrder:2,status:'draft'};
    assert.equal((await req(`/admin/opc/chapters/${stepId}`,learner.token,chapter)).status,403);
    assert.equal((await req(`/admin/opc/chapters/${stepId}`,admin.token,chapter)).status,200);
    assert.equal(row('SELECT status FROM project_steps WHERE id=?',[stepId]).status,'draft');
    assert.equal((await req(`/admin/opc/chapters/${stepId}`,admin.token,{...chapter,status:'published'})).status,200);
  });
  await t.test('catalog excludes draft and never exposes bodies or URLs; content and progress honor entitlement dates',async()=>{
    let catalog=await req('/opc/curriculum');
    assert.equal(catalog.cache,'private, no-store');
    assert.deepEqual(catalog.data.phases[1].items.map(i=>i.id),[paid,preview]);
    assert.equal(catalog.data.phases[1].items[0].locked,true);
    assert.equal(catalog.data.phases[1].items[1].locked,false);
    assert.equal(JSON.stringify(catalog).includes('PRIVATE_BODY'),false);
    assert.equal(JSON.stringify(catalog).includes('https://example.com/private'),false);
    assert.equal((await req(`/opc/content/${paid}`,learner.token)).status,403);
    assert.equal((await req(`/opc/content/${preview}`)).status,200);
    assert.equal((await req(`/opc/content/${draft}`,admin.token)).status,404);
    assert.equal((await req(`/me/progress/${paid}`,learner.token,{status:'completed'})).status,403);
    assert.equal((await req(`/me/progress/${draft}`,admin.token,{status:'completed'})).status,404);
    run("INSERT INTO entitlements(user_id,pack_id,status,starts_at,expires_at) VALUES(?,?,'active','2000-01-01','2001-01-01')",[learner.id,packId]);
    assert.equal((await req(`/opc/content/${paid}`,learner.token)).status,403);
    run("UPDATE entitlements SET starts_at='2999-01-01',expires_at=NULL WHERE user_id=?",[learner.id]);
    assert.equal((await req(`/opc/content/${paid}`,learner.token)).status,403);
    run("UPDATE entitlements SET starts_at='2000-01-01' WHERE user_id=?",[learner.id]);
    assert.equal((await req(`/opc/content/${paid}`,learner.token)).data.item.body,'PRIVATE_BODY');
    assert.equal((await req(`/me/progress/${paid}`,learner.token,{status:'completed'})).status,200);
    catalog=await req('/opc/curriculum',learner.token);
    assert.equal(catalog.data.phases[1].items[0].progress,'completed');
    assert.equal((await req('/opc/curriculum',other.token)).data.phases[1].items[0].progress,null);
    run("UPDATE project_steps SET status='draft' WHERE id=?",[stepId]);
    assert.equal((await req('/opc/curriculum',admin.token)).data.phases[1].items.length,0);
    assert.equal((await req(`/opc/content/${paid}`,admin.token)).status,404);
    run("UPDATE project_steps SET status='published' WHERE id=?",[stepId]);
    run("UPDATE learning_paths SET status='draft' WHERE id=?",[pathId]);
    assert.equal((await req('/opc/curriculum',admin.token)).data.phases[1].items.length,0);
    run("UPDATE learning_paths SET status='published' WHERE id=?",[pathId]);
  });
  await t.test('personal product is private, versioned, persists milestones and outcomes without touching workspace notes',async()=>{
    assert.equal((await req('/me/opc/product')).status,401);
    const initial=await req('/me/opc/product',learner.token);
    assert.deepEqual(initial.data.product,emptyProduct());
    const product={...emptyProduct(),name:'我的测试产品',type:'Web',phase:2};
    product.milestones[0]='done'; product.milestones[1]='doing';
    product.outcomes=[{phase:2,summary:'完成 MVP',url:'https://example.com',updatedAt:new Date().toISOString()}];
    assert.equal((await req('/me/opc/product',learner.token,product)).status,428);
    const saved=await req('/me/opc/product',learner.token,product,{'If-Match':initial.data.version});
    assert.equal(saved.status,200);
    assert.deepEqual((await req('/me/opc/product',learner.token)).data.product,product);
    assert.equal((await req('/me/opc/product',other.token)).data.product.name,'');
    assert.equal((await req('/me/opc/product',learner.token,{...product,name:'过期更新'},{'If-Match':initial.data.version})).status,409);
    for(const invalid of [{...product,phase:0},{...product,milestones:[]},{...product,userId:other.id},{...product,outcomes:[...product.outcomes,...product.outcomes]}]) assert.equal((await req('/me/opc/product',learner.token,invalid,{'If-Match':saved.data.version})).status,400);
    assert.equal(row('SELECT COUNT(*) n FROM workspace_state').n,0);
    assert.deepEqual((await req('/me/opc/product',learner.token)).data.product,product);
  });
});
