import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { resourceCategory,resourceTags,resourceArt,filterResources,resourceDate,resourceStages,featuredResources,RESOURCE_CATEGORIES } from '../src/resource-model.js';
import {RESOURCE_COURSE_PHASES,resourceCoursePhases,resourceLibraryItems,resourceHighlights,resourcePurpose,resourceAction,resourceAccess,resourcePrimaryCategories} from '../src/resource-library-model.js';
import {readFileSync} from 'node:fs';
test('resource library keeps five phases with chapter priority and keyword fallback',()=>{
 assert.equal(RESOURCE_COURSE_PHASES.length,5);
 assert.deepEqual(resourceCoursePhases({title:'支付上线需求',step_title:'第 4 章 收款与商业化'}),['business']);
 assert.deepEqual(resourceCoursePhases({title:'PRD 需求验证'}),['opportunity']);
 assert.deepEqual(resourceCoursePhases({title:'部署与支付清单'}),['launch','business']);
 assert.deepEqual(resourceCoursePhases({title:'无相关关键词'}),[]);
});
test('resource library combines course phase, type and multi-term search without inventing or mutating resources',()=>{
 const items=[{id:1,type:'document',title:'第 1 章章节大纲',step_title:'第 1 章 产品与机会',pack_title:'课程',summary:'发现需求',created_at:'2026-01-01'},{id:2,type:'prompt',title:'开发指令',step_title:'第 2 章 AI 产品开发',pack_title:'课程',created_at:'2026-02-01'},{id:3,type:'template',title:'验证模板',step_title:'第 1 章 产品与机会',pack_title:'课程'}];
 const before=structuredClone(items);
 assert.deepEqual(resourceLibraryItems(items,{phase:'build',category:'prompt',query:'开发 课程'}).map(i=>i.id),[2]);
 assert.deepEqual(resourceLibraryItems(items,{phase:'opportunity',category:'prompt'}),[]);
 assert.deepEqual(resourceLibraryItems(items,{query:'AI 产品开发'}).map(i=>i.id),[2]);
 assert.deepEqual(items,before);
});
test('resource highlights contain at most three actual records and chapter order is natural',()=>{
 const items=[5,3,1,2,4].map((n,i)=>({id:n,title:`第 ${n} 章章节大纲`,step_title:`第 ${n} 章`,pack_title:'课程',created_at:'2026-01-01',locked:n===1,is_featured:n===4?1:0}));
 assert.deepEqual(resourceLibraryItems(items).map(i=>i.id),[1,2,3,4,5]);
 assert.deepEqual(resourceHighlights(items).map(i=>i.id),[4,2,3]);
 assert.deepEqual(resourceHighlights([]),[]);
 assert.deepEqual(resourcePrimaryCategories([{title:'大纲',type:'document'}]),['all','learning']);
});
test('resource purpose/action labels do not promise phantom downloads, unlocked access or editable templates',()=>{
 assert.equal(resourcePurpose({summary:'发现市场机会 核心问题：做什么？ 阶段成果：产品定位'}),'发现市场机会');
 assert.ok(resourcePurpose({summary:'内容'.repeat(100)}).length<=64);
 assert.equal(resourceAction({title:'章节大纲'}),'阅读大纲');
 assert.equal(resourceAction({title:'章节大纲',locked:true}),'查看学习权益');
 assert.equal(resourceAction({type:'prompt'}),'查看 Prompt');
 assert.equal(resourceAccess({locked:true,is_preview:1}),'课程专享');
 assert.equal(resourceAccess({is_preview:1}),'免费预览');
 assert.equal(resourceAccess({}),'可访问');
});
test('resource design keeps actual reader and safe scoped styles without importing mock catalogue examples',()=>{
 const page=readFileSync(new URL('../src/ResourceCenter.jsx',import.meta.url),'utf8'),css=readFileSync(new URL('../src/resource-library-refinement.css',import.meta.url),'utf8');
 assert.match(page,/api\('\/resources'\)/);assert.match(page,/resourceHighlights\(items\)/);assert.match(page,/resourcePurpose\(resource\)/);
 assert.match(page,/navigate\('\/favorites'\)/);assert.match(page,/aria-label="课程阶段"/);assert.match(page,/resource.locked\?/);
 assert.doesNotMatch(page,/PRD 产品需求模板|MVP 开发 Prompt|Stripe|rd-card-art/);
 assert.match(page,/分类示意/);assert.match(page,/ResourceReader key=\{modal.id\}/);assert.match(css,/max-width:500px/);
 assert.doesNotMatch(css,/\.ws-sidebar|\.ws-topbar|\.ls-/);
});
test('resource discovery adds Skill/video categories and keyword-based stage filtering',()=>{
 assert.equal(RESOURCE_CATEGORIES.length,10);
 assert.equal(resourceCategory({title:'Claude Code Skill 最佳实践',type:'document'}),'skill');
 assert.equal(resourceCategory({title:'部署视频',type:'video'}),'video');
 assert.equal(resourceCategory({title:'技术 Skills 模板',type:'template'}),'skill');
 const resources=[{id:1,title:'PRD 需求验证',type:'template',created_at:'2026-01-01'},{id:2,title:'Stripe 支付上线清单',type:'checklist',created_at:'2026-02-01'},{id:3,title:'未归类资料',type:'download',created_at:'2026-03-01'}];
 assert.deepEqual(resourceStages(resources[0]),['validation']);
 assert.deepEqual(resourceStages(resources[1]),['launch','business']);
 assert.deepEqual(resourceStages(resources[2]),[]);
 assert.deepEqual(filterResources(resources,{stage:'business'}).map(i=>i.id),[2]);
 assert.deepEqual(filterResources(resources,{stage:'business',query:'PRD'}),[]);
 assert.deepEqual(filterResources(resources,{query:'undefined'}),[]);
});
test('featured discovery prioritizes CMS recommendations without fabricating records',()=>{
 const items=[{id:1,title:'旧精选',created_at:'2026-01-01',is_featured:1},{id:2,title:'新资料',created_at:'2026-02-01',is_featured:0},{id:3,title:'新精选',created_at:'2026-03-01',is_featured:1}];
 assert.deepEqual(featuredResources(items,2).map(i=>i.id),[3,1]);
 assert.deepEqual(items.map(i=>i.id),[1,2,3]);
 assert.deepEqual(featuredResources([]),[]);
});
test('resource taxonomy and search use actual metadata without mutating catalog',()=>{
 const items=[{id:1,title:'PRD 模板',type:'template',pack_title:'AI OPC',created_at:'2026-01-01',locked:false},{id:2,title:'Codex 开发指令',type:'prompt',pack_title:'AI OPC',created_at:'2026-02-01',locked:true},{id:3,title:'Docker 部署检查清单',type:'checklist',created_at:'2026-03-01',locked:false}];
 assert.deepEqual(items.map(resourceCategory),['template','prompt','checklist']);
 assert.equal(resourceCategory({title:'工具选型清单',type:'document'}),'tools');
 assert.equal(resourceCategory({title:'产品案例复盘',type:'document'}),'case');
 assert.deepEqual(resourceTags(items[1]),['Codex','Prompt']);
 assert.deepEqual(filterResources(items,{query:'codex opc'}).map(i=>i.id),[2]);
 assert.deepEqual(filterResources(items,{category:'prompt',tag:'PRD'}),[]);
 assert.deepEqual(filterResources(items,{sort:'accessible'}).map(i=>i.id),[3,1,2]);
 assert.deepEqual(filterResources(items).map(i=>i.id),[3,2,1]);
 assert.equal(items[0].id,1);
 assert.equal(resourceArt({title:'支付接入',type:'document'}),'payment');
 assert.equal(resourceArt(items[2]),'deploy');
 assert.equal(resourceDate('2026-09-26 12:00:00'),'2026-09-26');
 assert.equal(resourceDate(null),'日期待完善');
});
test('resource catalog hides drafts and bodies and honors entitlement dates',async t=>{
 const temp=mkdtempSync(path.join(tmpdir(),'oneshowlearn-resources-test-'));
 Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:path.join(temp,'test.db'),UPLOAD_DIR:path.join(temp,'uploads'),JWT_SECRET:'resources-tests-only'});
 const {db,row,run}=await import('../server/db.mjs');
 const {signUser}=await import('../server/auth.mjs');
 const {createApp}=await import('../server/index.mjs');
 const server=createApp().listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();rmSync(temp,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${server.address().port}/api`;
 const request=async(url,token)=>{const res=await fetch(base+url,{headers:token?{Authorization:`Bearer ${token}`}:{}});return{status:res.status,data:await res.json(),cache:res.headers.get('cache-control')};};
 const uid=Number(run("INSERT INTO users(email,password_hash,name,email_verified) VALUES('resource@example.com','unused','Resource Learner',1)").lastInsertRowid);
 const token=signUser(row('SELECT * FROM users WHERE id=?',[uid]));
 const pathId=Number(run("INSERT INTO learning_paths(slug,title,status) VALUES('resources','Resources','published')").lastInsertRowid);
 const packId=Number(run("INSERT INTO project_packs(path_id,slug,title,status) VALUES(?,'resource-pack','Resource Pack','published')",[pathId]).lastInsertRowid);
 const stepId=Number(run("INSERT INTO project_steps(pack_id,title,summary,status) VALUES(?,'Chapter','Public chapter summary','published')",[packId]).lastInsertRowid);
 const add=(status,preview=0)=>Number(run("INSERT INTO content_items(step_id,type,title,body,resource_url,status,is_preview) VALUES(?,'document','Resource','PRIVATE_BODY','https://example.com/private.pdf',?,?)",[stepId,status,preview]).lastInsertRowid);
 const paid=add('published'),free=add('published',1);add('draft');
 const catalog=await request('/resources');
 assert.equal(catalog.cache,'private, no-store');
 assert.deepEqual(catalog.data.items.map(i=>i.id),[free,paid]);
 assert.equal(catalog.data.items[0].locked,false);assert.equal(catalog.data.items[1].locked,true);
 assert.equal(JSON.stringify(catalog).includes('PRIVATE_BODY'),false);
 assert.equal(JSON.stringify(catalog).includes('private.pdf'),false);
 assert.equal((await request(`/projects/resource-pack/content/${paid}`,token)).status,403);
 assert.equal((await request(`/projects/resource-pack/content/${free}`)).status,200);
 run("INSERT INTO entitlements(user_id,pack_id,status,starts_at,expires_at) VALUES(?,?,'active','2000-01-01','2001-01-01')",[uid,packId]);
 assert.equal((await request('/resources',token)).data.items[1].locked,true);
 run("UPDATE entitlements SET starts_at='2999-01-01',expires_at=NULL WHERE user_id=?",[uid]);
 assert.equal((await request('/resources',token)).data.items[1].locked,true);
 run("UPDATE entitlements SET starts_at='2000-01-01' WHERE user_id=?",[uid]);
 assert.equal((await request('/resources',token)).data.items[1].locked,false);
 assert.equal((await request(`/projects/resource-pack/content/${paid}`,token)).data.item.body,'PRIVATE_BODY');
  assert.equal((await request('/resources')).data.items[1].locked,true);
 run("INSERT INTO progress(user_id,content_item_id,status) VALUES(?,?,'completed')",[uid,paid]);
 assert.equal((await request('/resources',token)).data.items[1].progress,'completed');
 assert.equal((await request('/resources')).data.items[1].progress,null);
 for(const [table,id] of [['project_steps',stepId],['project_packs',packId],['learning_paths',pathId]]){
   run(`UPDATE ${table} SET status='draft' WHERE id=?`,[id]);
   assert.equal((await request('/resources',token)).data.items.length,0);
   assert.equal((await request(`/projects/resource-pack/content/${free}`,token)).status,404);
   run(`UPDATE ${table} SET status='published' WHERE id=?`,[id]);
 }
});
