import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { resourceCategory,resourceTags,resourceArt,filterResources,resourceDate } from '../src/resource-model.js';
test('resource taxonomy and search use actual metadata without mutating catalog',()=>{
 const items=[{id:1,title:'PRD 模板',type:'template',pack_title:'AI OPC',created_at:'2026-01-01',locked:false},{id:2,title:'Codex 开发指令',type:'prompt',pack_title:'AI OPC',created_at:'2026-02-01',locked:true},{id:3,title:'Docker 部署检查清单',type:'checklist',created_at:'2026-03-01',locked:false}];
 assert.deepEqual(items.map(resourceCategory),['template','prompt','checklist']);
 assert.equal(resourceCategory({title:'工具选型清单',type:'document'}),'tools');
 assert.equal(resourceCategory({title:'产品案例复盘',type:'document'}),'case');
 assert.deepEqual(resourceTags(items[1]),['Codex','Prompt']);
 assert.deepEqual(filterResources(items,{query:'codex opc'}).map(i=>i.id),[2]);
 assert.deepEqual(filterResources(items,{category:'prompt',tag:'PRD'}),[]);
 assert.deepEqual(filterResources(items,{sort:'accessible'}).map(i=>i.id),[3,1,2]);
 assert.deepEqual(filterResources(items).map(i=>i.id),[3,2,1]);
 assert.equal(items[0].id,1);
 assert.equal(resourceArt({title:'支付接入',type:'document'}),'payment');
 assert.equal(resourceArt(items[2]),'deploy');
 assert.equal(resourceDate('2026-09-26 12:00:00'),'2026-09-26');
 assert.equal(resourceDate(null),'日期待完善');
});
test('resource catalog hides drafts and bodies and honors entitlement dates',async t=>{
 const temp=mkdtempSync(path.join(tmpdir(),'oneshowlearn-resources-test-'));
 Object.assign(process.env,{NODE_ENV:'test',DATABASE_PATH:path.join(temp,'test.db'),UPLOAD_DIR:path.join(temp,'uploads'),JWT_SECRET:'resources-tests-only'});
 const {db,row,run}=await import('../server/db.mjs');
 const {signUser}=await import('../server/auth.mjs');
 const {createApp}=await import('../server/index.mjs');
 const server=createApp().listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();rmSync(temp,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${server.address().port}/api`;
 const request=async(url,token)=>{const res=await fetch(base+url,{headers:token?{Authorization:`Bearer ${token}`}:{}});return{status:res.status,data:await res.json(),cache:res.headers.get('cache-control')};};
 const uid=Number(run("INSERT INTO users(email,password_hash,name,email_verified) VALUES('resource@example.com','unused','Resource Learner',1)").lastInsertRowid);
 const token=signUser(row('SELECT * FROM users WHERE id=?',[uid]));
 const pathId=Number(run("INSERT INTO learning_paths(slug,title,status) VALUES('resources','Resources','published')").lastInsertRowid);
 const packId=Number(run("INSERT INTO project_packs(path_id,slug,title,status) VALUES(?,'resource-pack','Resource Pack','published')",[pathId]).lastInsertRowid);
 const stepId=Number(run("INSERT INTO project_steps(pack_id,title,summary,status) VALUES(?,'Chapter','Public chapter summary','published')",[packId]).lastInsertRowid);
 const add=(status,preview=0)=>Number(run("INSERT INTO content_items(step_id,type,title,body,resource_url,status,is_preview) VALUES(?,'document','Resource','PRIVATE_BODY','https://example.com/private.pdf',?,?)",[stepId,status,preview]).lastInsertRowid);
 const paid=add('published'),free=add('published',1);add('draft');
 const catalog=await request('/resources');
 assert.equal(catalog.cache,'private, no-store');
 assert.deepEqual(catalog.data.items.map(i=>i.id),[free,paid]);
 assert.equal(catalog.data.items[0].locked,false);assert.equal(catalog.data.items[1].locked,true);
 assert.equal(JSON.stringify(catalog).includes('PRIVATE_BODY'),false);
 assert.equal(JSON.stringify(catalog).includes('private.pdf'),false);
 assert.equal((await request(`/projects/resource-pack/content/${paid}`,token)).status,403);
 assert.equal((await request(`/projects/resource-pack/content/${free}`)).status,200);
 run("INSERT INTO entitlements(user_id,pack_id,status,starts_at,expires_at) VALUES(?,?,'active','2000-01-01','2001-01-01')",[uid,packId]);
 assert.equal((await request('/resources',token)).data.items[1].locked,true);
 run("UPDATE entitlements SET starts_at='2999-01-01',expires_at=NULL WHERE user_id=?",[uid]);
 assert.equal((await request('/resources',token)).data.items[1].locked,true);
 run("UPDATE entitlements SET starts_at='2000-01-01' WHERE user_id=?",[uid]);
 assert.equal((await request('/resources',token)).data.items[1].locked,false);
 assert.equal((await request(`/projects/resource-pack/content/${paid}`,token)).data.item.body,'PRIVATE_BODY');
  assert.equal((await request('/resources')).data.items[1].locked,true);
 run("INSERT INTO progress(user_id,content_item_id,status) VALUES(?,?,'completed')",[uid,paid]);
 assert.equal((await request('/resources',token)).data.items[1].progress,'completed');
 assert.equal((await request('/resources')).data.items[1].progress,null);
 for(const [table,id] of [['project_steps',stepId],['project_packs',packId],['learning_paths',pathId]]){
   run(`UPDATE ${table} SET status='draft' WHERE id=?`,[id]);
   assert.equal((await request('/resources',token)).data.items.length,0);
   assert.equal((await request(`/projects/resource-pack/content/${free}`,token)).status,404);
   run(`UPDATE ${table} SET status='published' WHERE id=?`,[id]);
 }
});
