import {useEffect,useState} from 'react';
import {ArrowRight,CheckCircle,Code,Cube,FileText,Plus,Star,Trophy} from '@phosphor-icons/react';
import {api} from './api.js';
import {ACHIEVEMENT_TYPES,STAGES,liveAchievements,liveNotes,matchText,monthCount,shortDate,tagsFromText} from './personal-model.js';
import {Empty,Gate,Modal,Panel,PersonalHeading,Promo,SafeLink} from './PersonalShared.jsx';
import webArt from './assets/project-web-cover-v1.webp';
import codeArt from './assets/resources-code-v1.webp';
import docArt from './assets/resources-prd-v1.webp';
const artwork={product:webArt,code:codeArt,document:docArt,work:docArt};
const blank=()=>({id:crypto.randomUUID(),title:'',description:'',type:'product',stage:'building',url:'',tags:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export function AchievementsWorkspace({model,navigate,notify,query,setQuery}){
 const [category,setCategory]=useState('all'),[sort,setSort]=useState('newest'),[draft,setDraft]=useState(null),[tagText,setTagText]=useState(''),[detail,setDetail]=useState(null),[error,setError]=useState(''),[product,setProduct]=useState(null);
 useEffect(()=>{if(!model.user)return;let active=true;api('/me/opc/product').then(d=>active&&setProduct(d.product)).catch(()=>{});return()=>{active=false;};},[model.user?.id]);
 const achievements=liveAchievements(model.state);
 const shown=achievements.filter(a=>(category==='all'||a.type===category)&&matchText(a,query)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh-CN'):new Date(b.updatedAt)-new Date(a.updatedAt));
 const edit=item=>{if(!model.user)return navigate('/login');setDraft(item||blank());setTagText((item?.tags||[]).join(', '));setError('');setDetail(null);};
 const save=async e=>{e.preventDefault();if(!draft.title.trim())return;const item={...draft,title:draft.title.trim(),tags:tagsFromText(tagText),updatedAt:new Date().toISOString()};if(await model.saveState({...model.state,achievements:[item,...(model.state.achievements||[]).filter(a=>a.id!==item.id)]})){setDraft(null);notify('成果已保存，仅当前账号可见');}else setError('保存未成功，请检查链接、标签长度，或稍后重试。');};
 const archive=async item=>{if(await model.saveState({...model.state,achievements:(model.state.achievements||[]).map(a=>a.id===item.id?{...a,deletedAt:new Date().toISOString()}:a)})){setDetail(null);notify('成果已归档，可从归档列表恢复');}};
 const archived=(model.state.achievements||[]).filter(a=>a.deletedAt);
 const stages=[...achievements.map(a=>({title:a.title,description:`${STAGES[a.stage]} · 个人记录`,date:a.updatedAt,action:()=>setDetail(a)})),...(product?.outcomes||[]).map(o=>({title:`AI OPC 第 ${o.phase} 阶段成果`,description:o.summary,date:o.updatedAt,action:()=>navigate(`/opc/phase/${o.phase}`)}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5);
 return <div className="ps-layout"><div className="ps-main"><PersonalHeading title="我的成果" subtitle="记录每一个从想法到实现的里程碑，见证你的成长。" quote="一个人的力量，也可以创造不平凡的产品。" navigate={navigate}/><div className="ac-action"><button className="ps-text" onClick={()=>setDetail({archive:true})}>已归档 ({archived.length})</button><button className="ps-primary" onClick={()=>edit()}><Plus size={16}/>新建成果</button></div><section className="ac-metrics">{[[Cube,achievements.filter(a=>a.type==='product'&&a.stage==='launched'),'已上线项目'],[FileText,achievements.filter(a=>a.type==='document'),'成果文档'],[Code,achievements.filter(a=>a.type==='code'),'代码项目'],[Star,[],'官方证书']].map(([Icon,items,label],i)=><div key={label}><span className={`ps-tile ps-tone-${i}`}><Icon size={27}/></span><div><strong>{items.length}</strong><p>{label}</p><small>{label==='官方证书'?'发放功能待开放':`本月新增 ${monthCount(items)} 项`}</small></div></div>)}</section><Gate model={model} navigate={navigate}><div className="ps-catalog-toolbar"><div className="ps-tabs">{ACHIEVEMENT_TYPES.map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label} ({id==='all'?achievements.length:achievements.filter(a=>a.type===id).length})</button>)}</div><select aria-label="成果排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">最新更新</option><option value="title">按名称</option></select></div>{query&&<div className="ps-filter-label">搜索：{query}<button onClick={()=>setQuery('')}>清除</button></div>}
 {shown.length?<div className="ac-grid">{shown.map(item=><article className="ac-card" key={item.id}><header><span className="ps-label">{ACHIEVEMENT_TYPES.find(t=>t[0]===item.type)?.[1]}</span><span className={`ac-stage ac-stage-${item.stage}`}>{STAGES[item.stage]}</span><button className="ps-text" aria-label={`编辑${item.title}`} onClick={()=>edit(item)}>编辑</button></header><button className="ac-open" onClick={()=>setDetail(item)}><h2>{item.title}</h2><p>{item.description||'记录这次实践的目标、过程和结果。'}</p><div><img src={artwork[item.type]} alt=""/><small>分类示意</small></div></button><div className="ps-inline-tags">{item.tags.map(t=><span key={t}>{t}</span>)}</div><footer><span>{shortDate(item.updatedAt)}</span><button className="ps-text" onClick={()=>setDetail(item)}>查看成果<ArrowRight size={14}/></button></footer></article>)}</div>:<Empty title={category==='certificate'?'证书功能尚未开放':achievements.length?'这个分类还没有成果':'小小的成果，也是巨大的进步'} action={category==='certificate'?'继续学习':'记录我的第一个成果'} onAction={()=>category==='certificate'?navigate('/opc'):edit()} Icon={Trophy}>{category==='certificate'?'完成标准与评审规则明确后，再提供正式证书。':'一个原型、一份 PRD、一个上线链接，都值得认真记录。'}</Empty>}</Gate></div><aside className="ps-rail"><Panel title="成长数据"><p className="ps-muted">持续学习，持续创造</p><div className="ac-growth">{[[BookOpenTextFallback,model.stats.completedItems,'学完内容'],[Cube,achievements.length,'成果记录'],[FileText,liveNotes(model.state).length,'学习笔记'],[Star,model.stats.streakDays,'连续学习天数']].map(([Icon,value,label],i)=><div key={label}><span className={`ps-tile ps-tone-${i}`}><Icon size={23}/></span><span><strong>{value||0}</strong><small>{label}</small></span></div>)}</div></Panel><Panel title="里程碑"><div className="ac-timeline">{stages.map((s,i)=><button key={`${s.title}-${i}`} onClick={s.action}><CheckCircle size={23} weight="fill"/><span><strong>{s.title}</strong><small>{shortDate(s.date)}</small><p>{s.description}</p></span></button>)}{!stages.length&&<p className="ps-muted">记录第一项成果，留下你的第一个里程碑。</p>}<div><span/><p>下一站 · 做出属于你的产品<br/><small>按自己的节奏，继续向前。</small></p></div></div></Panel><section className="ac-quote"><h2>小小的成果，<br/>也是巨大的进步。</h2><span>— OneShowLearn</span></section><Promo kind="achievements" onClick={()=>edit()}/></aside>
 {draft&&<Modal title={achievements.some(a=>a.id===draft.id)?'编辑成果':'新建成果'} confirmClose close={()=>setDraft(null)}><form className="ps-form" onSubmit={save}><label>成果名称<input autoFocus required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div><label>成果类型<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{ACHIEVEMENT_TYPES.slice(1,-1).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>当前状态<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}>{Object.entries(STAGES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><label>成果描述<textarea rows={5} maxLength={5000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>作品或代码链接（可选）<input type="url" placeholder="https://" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>标签（逗号分隔，最多 8 个）<input value={tagText} maxLength={200} onChange={e=>setTagText(e.target.value)}/></label><p className="ps-muted">保存为私人记录，不会发布到社区或对外分享。</p>{error&&<p className="ps-alert" role="alert">{error}</p>}<button className="ps-primary" disabled={model.busy}>保存成果<ArrowRight size={15}/></button></form></Modal>}
 {detail&&!draft&&<Modal title={detail.archive?'已归档成果':detail.title} close={()=>setDetail(null)}><div className="ps-modal-body">{detail.archive?<>{archived.map(item=><div className="ac-archive" key={item.id}><strong>{item.title}</strong><button className="ps-outline" disabled={model.busy} onClick={async()=>{if(await model.saveState({...model.state,achievements:model.state.achievements.map(a=>a.id===item.id?{...a,deletedAt:null}:a)}))notify('成果已恢复');}}>恢复</button></div>)}{!archived.length&&<p>没有已归档的成果。</p>}</>:<><p className="ac-detail-text">{detail.description||'暂无说明'}</p><SafeLink url={detail.url}>打开作品链接</SafeLink><div className="ps-form-actions"><button className="ps-primary" onClick={()=>edit(detail)}>编辑成果</button><button className="ps-outline" disabled={model.busy} onClick={()=>archive(detail)}>归档成果</button></div></>}</div></Modal>}
 </div>;
}
const BookOpenTextFallback=FileText;
