import {useEffect,useState} from 'react';
import {api,money} from './api.js';
import {AdminRefundRecord} from './AdminRefundRecord.jsx';
import './functional-hardening.css';
export function AdminOrders(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[offset,setOffset]=useState(0),[q,setQ]=useState(''),[retry,setRetry]=useState(0),[refund,setRefund]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>api(`/admin/orders?offset=${offset}&q=${encodeURIComponent(q)}`).then(d=>{if(active){setData(d);setError('');}}).catch(e=>active&&setError(e.message)),200);return()=>{active=false;clearTimeout(timer);};},[offset,q,retry]);
 const paid=async id=>{if(busy||!window.confirm('仅在已核实实际到账后确认线下订单。此操作将开通课程权限。'))return;setBusy(true);try{await api(`/admin/orders/${id}/mark-paid`,{method:'POST'});setRetry(n=>n+1);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <><div className="admin-page-head"><div><h1>订单管理</h1><p>在线收款通过平台验签；线下收款人工确认；退款登记仅记录已核实的外部结果。</p></div></div>{error&&<p role="alert" className="admin-error">{error}<button onClick={()=>setRetry(n=>n+1)}>重试</button></p>}<section className="admin-panel"><label>查找订单号<input value={q} disabled={!!refund} onChange={e=>{setQ(e.target.value);setOffset(0);setData(null);}}/></label>{!data?<p>正在读取订单…</p>:<><div className="admin-table orders"><div className="tr head"><span>订单</span><span>用户</span><span>商品</span><span>金额</span><span>状态</span><span>操作</span></div>{data.items.map(o=><div className="tr" key={o.id}><span><strong>{o.order_no}</strong><small>{o.created_at}</small></span><span><strong>{o.name}</strong><small>{o.email}</small></span><span>{o.item_titles}</span><span>{money(o.amount_cents)}</span><span>{({paid:'已支付',pending:'待支付',refunded:'已退款',cancelled:'已关闭'})[o.status]||o.status}</span><span>{!o.online_provider&&o.status==='pending'&&<button disabled={busy||!!refund} onClick={()=>paid(o.id)}>确认线下收款</button>}{['paid','refunded'].includes(o.status)&&<button disabled={busy||!!refund} onClick={()=>setRefund(o.id)}>退款登记 / 记录</button>}</span></div>)}</div>{!data.items.length&&<p>没有匹配订单。</p>}<nav className="support-actions" aria-label="管理订单分页"><button disabled={offset===0||!!refund} onClick={()=>{setOffset(v=>Math.max(0,v-20));setData(null);}}>上一页</button><span>{data.total} 笔 · 第 {Math.floor(offset/20)+1} 页</span><button disabled={offset+20>=data.total||!!refund} onClick={()=>{setOffset(v=>v+20);setData(null);}}>下一页</button></nav></>}</section>{refund&&<AdminRefundRecord key={refund} orderId={refund} close={()=>setRefund(null)} onSaved={()=>setRetry(n=>n+1)}/>}</>;
}
