import {useEffect,useState} from 'react';
import {api} from './api.js';
import {Dialog} from './AdminDialog.jsx';
import {CommunityArticle} from './CommunityWorkspace.jsx';
import {COMMUNITY_CATEGORIES,COMMUNITY_SETTINGS,EMPTY_ARTICLE} from '../server/community-definition.mjs';
import './admin-cms.css';
import './admin-community.css';
import {CommunityImageUpload,CommunityImagePreview} from './CommunityImageUpload.jsx';

function Editor({initial,resources,close,saved}){
  const [record,setRecord]=useState(initial),[form,setForm]=useState(initial.kind==='settings'?{...COMMUNITY_SETTINGS,...initial.draft}:initial.draft),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[history,setHistory]=useState([]),[confirmAction,setConfirmAction]=useState('');
  const dirty=JSON.stringify(form)!==JSON.stringify(record.kind==='settings'?{...COMMUNITY_SETTINGS,...record.draft}:record.draft),config=record.kind==='settings';
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  useEffect(()=>{const before=e=>{if(dirty){e.preventDefault();e.returnValue='';}};const navigate=e=>{if(dirty&&!window.confirm('放弃未保存的社区内容？'))e.preventDefault();};window.addEventListener('beforeunload',before);window.addEventListener('oneshowlearn:before-navigate',navigate);return()=>{window.removeEventListener('beforeunload',before);window.removeEventListener('oneshowlearn:before-navigate',navigate);};},[dirty]);
  const exit=()=>{if(busy)return;if(dirty)setConfirmAction('discard');else close();};
  const action=async type=>{setBusy(true);setError('');setMessage('');try{
    if(type==='history'){setHistory((await api(`/admin/community/${record.id}/history`)).items);setMessage('可载入历史草稿，保存并发布后才会改变前台。');return;}
    const result=type==='save'?await api(`/admin/community${record.id?`/${record.id}`:''}`,{method:record.id?'PUT':'POST',headers:record.id?{'If-Match':String(record.version)}:{},body:JSON.stringify({kind:record.kind,draft:form})}):await api(`/admin/community/${record.id}/${type}`,{method:'POST',headers:{'If-Match':String(record.version)}});
    setRecord(result.item);setForm(result.item.kind==='settings'?{...COMMUNITY_SETTINGS,...result.item.draft}:result.item.draft);saved();setMessage(type==='save'?'草稿已保存，尚未改变前台。':type==='publish'?'已发布，用户刷新社区即可看到。':type==='archive'?'已归档，前台不再显示；可以恢复。':'已恢复原发布状态。');
  }catch(e){setError(e.message);}finally{setBusy(false);}};
  const field=(key,label,area=false,required=false)=><label>{label}{area?<textarea required={required} rows={key==='body'?16:3} value={form[key]} onChange={e=>set(key,e.target.value)} maxLength={key==='body'?100000:500}/>:<input required={required} value={form[key]} onChange={e=>set(key,e.target.value)} maxLength={['coverUrl','qrUrl'].includes(key)?2000:160}/>}</label>;
  const picture=(key,label,hint)=><CommunityImageUpload label={label} value={form[key]} onChange={value=>set(key,value)} onBusy={setBusy} onError={setError} hint={hint}/>;
  return <Dialog title={config?'社区页面与会员群设置':'编辑官方文章'} close={exit}><form className="platform-form" onSubmit={e=>{e.preventDefault();action('save');}}><fieldset disabled={busy}>{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-success" role="status">{message}</p>}{field('title',config?'广场标题':'文章标题',false,true)}{config?<><fieldset className="community-settings-fieldset"><legend>官方内容广场</legend>{field('eyebrow','横幅标签')}{field('description','广场介绍',true)}{field('tagline','补充说明',true)}{picture('heroImage','广场横幅插图','留空沿用当前社区插画；建议使用横向图片，图片中不要放入二维码。')}</fieldset><fieldset className="community-settings-fieldset"><legend>微信会员群</legend>{field('groupTitle','会员群标题',false,true)}{field('groupDescription','会员群说明',true)}{picture('qrUrl','微信群二维码','请上传真实、清晰且保留白边的二维码。支持 PNG / JPEG / WebP，最大 5MB。')}{field('groupInstructions','扫码入群说明',true)}<label>二维码有效期（北京时间，截止当天结束）<input type="date" value={form.groupExpiresAt} onChange={e=>set('groupExpiresAt',e.target.value)}/></label><p className="cms-hint">可留空；到期自动停止展示二维码，上传新码并调整日期、发布后恢复。</p><p className="cms-hint">本地上传文件存放在私有附件库，保存草稿不会开放图片。发布后二维码仍按下方范围校验；微信群本身的审核由微信管理。</p><label className="cms-checkbox"><input type="checkbox" checked={form.groupEnabled} onChange={e=>set('groupEnabled',e.target.checked)}/>启用微信群入口</label><label>二维码展示范围<select value={form.groupAudience} onChange={e=>set('groupAudience',e.target.value)}><option value="entitled">拥有任一有效课程权益的学员</option><option value="signed-in">所有已登录用户</option></select></label></fieldset><fieldset><legend>推荐资源（最多 8 项，按选择顺序）</legend><p className="cms-hint">引用已发布课程资料，阅读和下载仍检查原课程权限，不复制付费正文。</p>{resources.map(r=><label key={r.id} className="cms-checkbox"><input type="checkbox" checked={form.resourceIds.includes(r.id)} onChange={e=>set('resourceIds',e.target.checked?[...form.resourceIds,r.id]:form.resourceIds.filter(id=>id!==r.id))}/>{r.title} · {r.pack_title}</label>)}</fieldset></>:<>{field('summary','卡片摘要',true)}<div className="cms-form-row"><label>文章分类<select value={form.category} onChange={e=>set('category',e.target.value)}>{COMMUNITY_CATEGORIES.slice(1).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{field('topic','学习专题（同名自动归组）')}</div>{picture('coverUrl','文章封面','建议使用 16:9 横向图片；留空使用分类封面。支持 5MB 以内 PNG / JPEG / WebP。')}<div className="cms-form-row"><label className="cms-checkbox"><input type="checkbox" checked={form.pinned} onChange={e=>set('pinned',e.target.checked)}/>置顶</label><label className="cms-checkbox"><input type="checkbox" checked={form.recommended} onChange={e=>set('recommended',e.target.checked)}/>官方推荐</label></div>{field('body','正文（Markdown，支持标题、列表、表格和代码）',true,true)}<p className="cms-hint">官方社区文章发布后向已登录用户开放，请勿复制付费课件或私人笔记。课程资料请通过推荐资源引用。</p></>}
    <div className="cms-actions"><button type="button" onClick={()=>setPreview(true)}>预览</button><button type="submit">{busy?'处理中…':'保存草稿'}</button><button type="button" className="admin-primary" disabled={!record.id||dirty} onClick={()=>{setConfirmAction('publish');}}>确认发布</button>{record.id&&<><button type="button" disabled={dirty} onClick={()=>{setConfirmAction(record.archived?'restore':'archive');}}>{record.archived?'恢复':'归档'}</button><button type="button" onClick={()=>action('history')}>发布历史</button></>}</div><p className="cms-hint">{dirty?'有未保存的修改。':'修改草稿不会影响当前已发布版本。'} 发布和归档均可恢复；不会删除用户学习数据。</p>{history.map(h=><button type="button" key={h.id} onClick={()=>{if(!dirty||window.confirm('用历史版本替换当前未保存草稿？'))setForm(config?{...COMMUNITY_SETTINGS,...h.draft}:h.draft);}}>载入版本 #{h.id} · {h.created_at}</button>)}</fieldset></form>
    {confirmAction&&<Dialog title="确认社区发布操作" close={()=>!busy&&setConfirmAction('')}><div className="oc-reading"><p>{confirmAction==='discard'?'关闭将放弃未保存的修改，已保存的内容不受影响。':confirmAction==='publish'?'确认将已保存的草稿发布到学习社区？':confirmAction==='archive'?'归档后将在前台隐藏内容，可以随时恢复。':'确认恢复此内容的原发布状态？'}</p><div className="cms-actions"><button disabled={busy} onClick={()=>setConfirmAction('')}>取消操作</button><button className="admin-primary" disabled={busy} onClick={async()=>{if(confirmAction==='discard'){close();return;}await action(confirmAction);setConfirmAction('');}}>确定操作</button></div></div></Dialog>}
    {preview&&<Dialog title="仅管理员可见 · 未发布预览" close={()=>setPreview(false)}>{config?<div className="oc-reading"><h1>{form.title}</h1><p>{form.description}</p><p>{form.tagline}</p><CommunityImagePreview value={form.heroImage} alt="广场横幅预览"/><hr/><h2>{form.groupTitle}</h2><p>{form.groupDescription}</p><p>入群方式：{form.groupEnabled?'启用':'准备中'} · {form.groupAudience==='entitled'?'有效课程权益学员':'所有登录用户'}</p><CommunityImagePreview value={form.qrUrl} alt="会员群二维码预览"/><p>{form.groupInstructions}</p><p>有效期：{form.groupExpiresAt||'未设置'}</p><h3>推荐资源</h3>{form.resourceIds.map(id=><p key={id}>{resources.find(r=>r.id===id)?.title||`资料 #${id} · 当前未发布`}</p>)}</div>:<CommunityArticle article={form} preview/>}</Dialog>}
  </Dialog>;
}
export function AdminCommunity(){
  const [items,setItems]=useState([]),[resources,setResources]=useState([]),[editing,setEditing]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState('');
  const load=async()=>{setError('');try{const [a,b]=await Promise.all([api('/admin/community'),api('/resources')]);setItems(a.items);setResources(b.items);}catch(e){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const config=items.find(i=>i.kind==='settings');
  const openSettings=()=>setEditing(config||{kind:'settings',draft:COMMUNITY_SETTINGS});
  return <div className="cms-page"><div className="admin-page-head"><div><span>OFFICIAL COMMUNITY</span><h1>官方社区内容</h1><p>维护文章、学习专题、推荐资源和微信会员群；保存草稿后明确发布。</p></div><div className="cms-actions"><button disabled={loading||Boolean(error)} onClick={openSettings}>页面与会员群设置</button><button className="admin-primary" onClick={()=>setEditing({kind:'article',draft:EMPTY_ARTICLE})}>新建官方文章</button></div></div>{error&&<p className="admin-error" role="alert">{error}<button onClick={load}>重新加载</button></p>}<section className="community-config-overview" aria-label="社区配置入口"><article><h2>官方内容广场配置</h2><p>维护广场标题、介绍、横幅插图与推荐资源；文章在下方独立编辑发布。</p><small>{config?.published?'已有发布版本，编辑草稿不影响前台。':'尚未发布配置，前台使用默认广场文案。'}</small><button disabled={loading||Boolean(error)} onClick={openSettings}>配置内容广场</button></article><article><h2>微信会员群配置</h2><p>直接上传、更换二维码，配置入群说明、有效期和可见人群。</p><small>{config?.draft.qrUrl?'草稿中已有二维码；以确认发布的版本为准。':'尚未上传二维码，请在设置中添加真实群码。'}</small><button disabled={loading||Boolean(error)} onClick={openSettings}>上传 / 更换群二维码</button></article></section><h2 className="community-section-title">官方文章管理</h2><div className="community-list-filter"><input placeholder="搜索文章…" aria-label="搜索官方文章" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={load}>刷新</button></div>{loading?<p>正在加载…</p>:<div className="cms-course-grid">{items.filter(i=>i.kind==='article'&&i.draft.title.toLowerCase().includes(query.toLowerCase())).map(item=><article key={item.id}><div className="cms-course-top"><span>#{item.id}</span><span>{item.archived?'已归档':item.published?'已有发布版本':'私人草稿'}</span></div><h2>{item.draft.title}</h2><p>{item.draft.summary||'尚未填写摘要'}</p><small>{COMMUNITY_CATEGORIES.find(c=>c[0]===item.draft.category)?.[1]}{item.draft.topic?` · ${item.draft.topic}`:''}</small><footer><button onClick={()=>setEditing(item)}>编辑与发布</button></footer></article>)}</div>}{!loading&&!items.some(i=>i.kind==='article')&&<div className="cms-empty">尚未创建官方文章。新文章先保存为草稿，预览确认后再发布。</div>}{editing&&<Editor key={editing.id||editing.kind} initial={editing} resources={resources} close={()=>setEditing(null)} saved={load}/>}</div>;
}
