import {useEffect,useState} from 'react';
import {api,money} from './api.js';
import './commercial-admin.css';
const states={submitting:'提交中',uploading:'上传中',running:'解析中',uncertain:'待核验',review:'待审核',imported:'已导入草稿',failed:'解析失败',closed:'已关闭'};
function useData(path){const [data,setData]=useState(null),[error,setError]=useState(''),[v,retry]=useState(0);useEffect(()=>{let active=true;setData(null);setError('');api(path).then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[path,v]);return {data,error,setError,reload:()=>retry(n=>n+1)};}
function Notice({state}){return state.error?<p className="admin-error" role="alert">{state.error} <button onClick={state.reload}>重新加载</button></p>:!state.data?<p role="status">正在读取…</p>:null;}
function Switch({field,label,onSaved}){const s=useData('/admin/commercial/settings'),[busy,setBusy]=useState(false);return <div className="ca-switch"><Notice state={s}/>{s.data&&<><span>{label}：{s.data[field]?'已开启':'已暂停'}</span><button disabled={busy} onClick={async()=>{setBusy(true);try{await api('/admin/commercial/settings',{method:'PUT',headers:{'If-Match':String(s.data.version)},body:JSON.stringify({telemetry_enabled:Boolean(s.data.telemetry_enabled),parser_enabled:Boolean(s.data.parser_enabled),[field]:!s.data[field]})});s.reload();onSaved();}catch(e){s.setError(e.message);}finally{setBusy(false);}}}>{s.data[field]?'暂停':'开启'}{label}</button></>}</div>;}
const routeNames={home:'首页',offer:'完整课程介绍',lesson:'课程课时',projects:'实战项目',workbench:'工作台',login:'登录',register:'注册',resources:'资源中心',tutor:'AI 导师',catalog:'课程目录',community:'社区',notes:'笔记',favorites:'收藏',outcomes:'成果',account:'设置'};
function Table({head,rows}){return rows.length?<table><thead><tr>{head.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>:<p>暂无真实样本。</p>;}
export function AdminAnalytics(){const [days,setDays]=useState(7),s=useData('/admin/analytics?days='+days),d=s.data;return <div className="ca-page"><div className="admin-page-head"><div><h1>经营与体验监测</h1><p>注册批次转化、站内访问与浏览器体验。</p></div><select aria-label="统计时间范围" value={days} onChange={e=>setDays(+e.target.value)}>{[7,30,90].map(n=><option key={n} value={n}>最近 {n} 天</option>)}</select></div><Switch field="telemetry_enabled" label="体验统计" onSaved={s.reload}/><Notice state={s}/>{d&&<>
 <section className="admin-panel"><h2>新注册学员转化</h2><p>同一注册批次，按注册 → 下单 → 核验付款 → 付款后学习活动统计；退款订单仍保留历史付款事实。</p><div className="admin-metrics">{[['注册',d.cohort.registered],['下单',d.cohort.checkout],['核验付款',d.cohort.paid],['付款后学习',d.cohort.learned]].map(([label,n])=><article key={label}><span>{label}</span><strong>{n}</strong></article>)}</div><p>注册到付款 {d.cohort.paidRate===null?'暂无样本':(d.cohort.paidRate*100).toFixed(1)+'%'} · 付款到学习 {d.cohort.learnedRate===null?'暂无样本':(d.cohort.learnedRate*100).toFixed(1)+'%'}</p></section>
 <section className="admin-panel"><h2>收款记录</h2><p>本期核验付款 {d.financial.orders} 笔 · 付款总额 {money(d.financial.grossCents)} · 本期核实登记退款 {money(d.financial.recordedRefundCents)}</p><small>付款与退款按各自记录时间统计；结算账单仍在支付平台核对。</small></section>
 <section className="admin-panel"><h2>站内访问</h2><p>开启后采集。匿名会话在页面刷新后重新计数，不作为独立访客人数。</p><Table head={['页面','浏览次数','页面会话']} rows={d.traffic.map(i=>[routeNames[i.route],i.views,i.sessions])}/></section>
 <section className="admin-panel"><h2>真实浏览器体验</h2><p>LCP：主要内容呈现；CLS：布局稳定性；INP：采样交互延迟近似值。各指标展示 P75，最近最多 {d.performanceSampleLimit} 条样本。SPA 导航只统计浏览事件，性能指标归属初始页面。</p><Table head={['页面','指标','样本','P75']} rows={d.performance.map(i=>[routeNames[i.route],i.metric,i.samples,i.metric==='CLS'?i.p75.toFixed(3):Math.round(i.p75)+' ms'])}/></section>
 <section className="admin-panel"><h2>前端异常</h2><p>只保留页面分类与异常类型，不记录正文、堆栈、私人内容或完整地址。保留 90 天，尊重 Do Not Track。</p><Table head={['页面','类型','次数']} rows={d.errors.map(i=>[routeNames[i.route],({runtime:'页面运行',promise:'异步请求',asset:'资源加载',api:'接口连接'})[i.metric],i.count])}/></section>
 </>}</div>;}
export function AdminParsing({navigate}){
 const [offset,setOffset]=useState(0),s=useData('/admin/parsing?offset='+offset),assets=useData('/admin/cms/assets'),[asset,setAsset]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[review,setReview]=useState(null),[message,setMessage]=useState('');
 const action=async fn=>{if(busy)return;setBusy(true);s.setError('');try{await fn();s.reload();}catch(e){s.setError(e.message);}finally{setBusy(false);}};
 return <div className="ca-page"><div className="admin-page-head"><div><h1>资料自动解析</h1><p>附件 → MinerU 解析 → 审核 → 资料库草稿 → 编排与发布。</p></div><button onClick={()=>navigate('/admin/assets')}>附件库</button></div><Switch field="parser_enabled" label="资料解析" onSaved={s.reload}/><Notice state={s}/>{message&&<p role="status">{message}</p>}{s.data&&<>
 <section className="admin-panel"><h2>提交文档</h2><p>服务器密钥：{s.data.configured?'已配置':'待配置 MINERU_API_KEY'}。支持 PDF、PPTX、DOCX 和图片，最大 200MB / 600 页；视频请准备字幕或文稿。</p><Notice state={assets}/><label>附件<select aria-label="待解析附件" value={asset} onChange={e=>setAsset(e.target.value)}><option value="">选择附件</option>{assets.data?.items.filter(a=>a.private&&/\.(pdf|pptx|docx|png|jpe?g|webp)$/i.test(a.original_name)).map(a=><option key={a.id} value={a.id}>{a.original_name}</option>)}</select></label><label className="admin-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>确认该附件可传给 MinerU 解析</label><button className="admin-primary" disabled={busy||!asset||!consent||!s.data.enabled||!s.data.configured} onClick={()=>action(async()=>{await api('/admin/parsing',{method:'POST',body:JSON.stringify({assetId:+asset,consent})});setMessage('任务已提交，后台定期查询，也可手动查询结果。');setConsent(false);})}>开始解析</button></section>
 <section className="admin-panel"><h2>解析任务</h2>{s.data.items.map(j=><article className="ca-job" key={j.id}><div><strong>{j.name}</strong><p>{states[j.state]} · {j.created_at}</p>{j.error&&<p>{j.error}</p>}</div><div>{['running','uncertain','uploading'].includes(j.state)&&<button disabled={busy} onClick={()=>action(()=>api('/admin/parsing/'+j.id+'/check',{method:'POST'}))}>查询原任务</button>}{j.state==='review'&&<button disabled={busy} onClick={()=>action(async()=>{const d=await api('/admin/parsing/'+j.id);setReview({...d,title:d.name});})}>审核正文</button>}{j.state==='imported'&&<button onClick={()=>navigate('/admin/library')}>查看资料库</button>}{!['closed','imported'].includes(j.state)&&<button disabled={busy} onClick={()=>{if(window.confirm('已核对 MinerU 原任务？关闭本地任务不会取消远端处理，原附件保留。'))action(()=>api('/admin/parsing/'+j.id+'/close',{method:'POST',headers:{'If-Match':String(j.version)},body:JSON.stringify({confirm:true})}));}}>关闭任务</button>}</div></article>)}{!s.data.items.length&&<p>还没有解析任务。</p>}<nav aria-label="解析任务分页"><button disabled={!offset||busy} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</button><span>{s.data.total} 项</span><button disabled={offset+20>=s.data.total||busy} onClick={()=>setOffset(v=>v+20)}>下一页</button></nav></section>
 </>}{review&&<section className="admin-panel" aria-label="审核解析正文"><h2>审核正文</h2><p>检查公式、表格、引用与私人信息。只导入文字草稿，原附件和既有资料保持不变。</p><label>资料标题<input value={review.title} maxLength={200} onChange={e=>setReview({...review,title:e.target.value})}/></label><label>Markdown 正文<textarea aria-label="解析正文" rows={16} value={review.body} onChange={e=>setReview({...review,body:e.target.value})}/></label><button className="admin-primary" disabled={busy||!review.title.trim()||!review.body.trim()} onClick={()=>action(async()=>{await api('/admin/parsing/'+review.id+'/import',{method:'POST',headers:{'If-Match':String(review.version)},body:JSON.stringify({title:review.title,body:review.body})});setReview(null);setMessage('已导入草稿，请关联课时、核对权限后发布。');})}>审核通过，导入草稿</button><button disabled={busy} onClick={()=>setReview(null)}>暂不导入</button></section>}</div>;
}
export function AdminCertificates(){
 const [offset,setOffset]=useState(0),s=useData('/admin/certificates?offset='+offset),[counts,setCounts]=useState({}),[busy,setBusy]=useState(false);
 const action=async fn=>{if(busy)return;setBusy(true);s.setError('');try{await fn();s.reload();}catch(e){s.setError(e.message);}finally{setBusy(false);}};
 return <div className="ca-page"><div className="admin-page-head"><div><h1>课程结业证书</h1><p>以正式目录和服务器完课记录，自动发放 OneShowLearn 结业证书。</p></div></div><Notice state={s}/>{s.data&&<><section className="admin-panel"><h2>发证课程与目录</h2><p>全部正式课时发布后，填写完整课时数并启用。教学内容变化后确认目录再恢复发证；既有证书保留原目录。</p>{s.data.courses.map(c=><article className="ca-job" key={c.id}><div><strong>{c.title}</strong><p>已发布 {c.total} 节 · 演示 {c.demo} 节 · {c.enabled?(c.current?'自动发证已启用':'目录变化，待确认'):'尚未启用'}</p></div><div><label>完整课时数<input aria-label={c.title+'完整课时数'} type="number" min={1} max={1000} value={counts[c.id]??''} placeholder="例如 40" onChange={e=>setCounts({...counts,[c.id]:e.target.value})}/></label><button disabled={busy||!counts[c.id]||c.demo>0} onClick={()=>{if(window.confirm('确认全部正式课时已发布，启用此目录自动发证？'))action(()=>api('/admin/certificates/courses/'+c.id,{method:'PUT',headers:{'If-Match':String(c.version)},body:JSON.stringify({enabled:true,expectedLessons:+counts[c.id]})}));}}>确认目录并启用</button>{Boolean(c.enabled)&&<button disabled={busy} onClick={()=>action(()=>api('/admin/certificates/courses/'+c.id,{method:'PUT',headers:{'If-Match':String(c.version)},body:JSON.stringify({enabled:false,expectedLessons:Math.max(1,c.total)})}))}>暂停新证书</button>}</div></article>)}</section><section className="admin-panel"><h2>颁发记录</h2>{s.data.items.map(c=><article className="ca-job" key={c.id}><div><strong>{c.recipient} · {c.course_title}</strong><p>{c.issued_at} · {c.revoked_at?'已撤销':'已颁发'}</p><small>{c.id}</small>{c.reason&&<p>{c.reason}</p>}</div>{!c.revoked_at&&<button disabled={busy} onClick={()=>{const reason=window.prompt('请填写撤销原因，原记录保留，学员可查看原因');if(reason?.trim())action(()=>api('/admin/certificates/'+c.id+'/revoke',{method:'POST',body:JSON.stringify({reason})}));}}>撤销证书</button>}</article>)}{!s.data.items.length&&<p>暂无颁发记录，完成全部正式课时后自动发放。</p>}<nav aria-label="证书分页"><button disabled={!offset||busy} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</button><span>{s.data.total} 项</span><button disabled={offset+20>=s.data.total||busy} onClick={()=>setOffset(v=>v+20)}>下一页</button></nav></section></>}</div>;
}
