import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpenText,FileText,Lightning,UsersThree,MagnifyingGlass,WechatLogo,Clock,ArrowUpRight,ShieldCheck} from '@phosphor-icons/react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {api} from './api.js';
import {Empty,Modal,Panel} from './PersonalShared.jsx';
import {COMMUNITY_CATEGORIES,COMMUNITY_SETTINGS} from '../server/community-definition.mjs';
import {ResourceReader} from './ResourceCenter.jsx';
import hero from './assets/community-hero-v1.webp';
import './community-official.css';

const categoryName=id=>COMMUNITY_CATEGORIES.find(c=>c[0]===id)?.[1]||'官方内容';
const date=value=>value?new Date(value).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}):'未发布';
export function CommunityArticle({article,preview=false}){
  return <article className="oc-reading"><span className="oc-kicker">{preview?'未发布预览 · ':''}{categoryName(article.category)}{article.topic?` / ${article.topic}`:''}</span><h1>{article.title}</h1><div className="oc-byline"><img src="/assets/oneshowlearn-brandmark.png" alt=""/><b>OneShowLearn 官方</b><time>{date(article.publishedAt)}</time></div>{article.summary&&<p className="oc-abstract">{article.summary}</p>}<div className="oc-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{img:({alt})=><span>{alt||'图片'}</span>,a:({href,children})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>}}>{article.body}</ReactMarkdown></div></article>;
}
function GroupCard({settings,onOpen}){return <section className="oc-group"><WechatLogo size={30}/><h2>{settings.groupTitle}</h2><p>{settings.groupDescription}</p><ul><li>交流产品开发经验</li><li>获取课程与资源更新</li><li>与同行分享实践心得</li></ul><button onClick={onOpen}>{settings.groupAccessible?'查看入群二维码':settings.groupReady?'查看加入方式':'了解会员学习群'}<ArrowRight size={16}/></button><small>{settings.groupExpired?'二维码已到期，官方更新后将重新开放':settings.groupReady?'二维码由 OneShowLearn 官方维护':'入群方式准备中，开放后将在这里更新'}</small></section>;}
export function CommunityWorkspace({model,navigate,notify,query='',setQuery}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[category,setCategory]=useState('all'),[topic,setTopic]=useState(''),[sort,setSort]=useState('latest'),[limit,setLimit]=useState(12),[selected,setSelected]=useState(null),[articleError,setArticleError]=useState(''),[articleLoading,setArticleLoading]=useState(false),[group,setGroup]=useState(false);
  const [resource,setResource]=useState(null);
  const revision=useRef(0),reading=useRef(0);
  const load=async()=>{const rev=++revision.current;setLoading(true);setError('');try{const d=await api('/community');if(rev===revision.current)setData(d);}catch(e){if(rev===revision.current)setError(e.message);}finally{if(rev===revision.current)setLoading(false);}};
  useEffect(()=>{load();return()=>{revision.current++;reading.current++;};},[]);
  useEffect(()=>setLimit(12),[category,topic,query,sort]);
  const openArticle=async item=>{const rev=++reading.current;setSelected(item);setArticleError('');setArticleLoading(true);try{const result=await api(`/community/articles/${item.id}`);if(rev===reading.current)setSelected(result.item);}catch(e){if(rev===reading.current)setArticleError(e.message);}finally{if(rev===reading.current)setArticleLoading(false);}};
  const settings=data?.settings||COMMUNITY_SETTINGS,items=data?.items||[],resources=data?.resources||[];
  const filtered=items.filter(i=>(category==='all'||i.category===category)&&(!topic||i.topic===topic)&&`${i.title} ${i.summary} ${i.topic}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(sort==='recommended'?Number(b.recommended)-Number(a.recommended):0)||b.publishedAt.localeCompare(a.publishedAt)||b.id-a.id);
  const topics=Array.from(new Set(items.map(i=>i.topic).filter(Boolean))).map(name=>({name,count:items.filter(i=>i.topic===name).length})).sort((a,b)=>b.count-a.count);
  const month=new Date().toLocaleDateString('en-CA',{year:'numeric',month:'2-digit',timeZone:'Asia/Shanghai'});
  const recent=items.filter(i=>new Date(i.publishedAt).toLocaleDateString('en-CA',{year:'numeric',month:'2-digit',timeZone:'Asia/Shanghai'})===month).length;
  const admin=['admin','editor'].includes(model.user?.role);
  return <div className="oc-page"><div className="oc-topline"><button className="oc-group-entry" onClick={()=>setGroup(true)}><WechatLogo size={20} weight="duotone"/>微信会员学习群<ArrowUpRight size={14}/></button><div><button onClick={()=>navigate('/notes')}>我的学习笔记</button>{admin&&<button onClick={()=>navigate('/admin/community')}>管理官方内容<ArrowUpRight size={14}/></button>}</div></div>
    <div className="oc-layout"><main className="oc-main"><section className="oc-hero"><img src={settings.heroImage||hero} alt="" onError={e=>{if(!e.currentTarget.src.endsWith(hero))e.currentTarget.src=hero;}}/><div className="oc-hero-copy"><span className="oc-kicker">{settings.eyebrow||COMMUNITY_SETTINGS.eyebrow}</span><h1>{settings.title}</h1><p>{settings.description}</p><small>{settings.tagline}</small></div><div className="oc-values">{[[BookOpenText,'实战干货','真实项目经验分享'],[FileText,'模板资源','可复用的实践工具'],[Lightning,'持续更新','关注产品开发与增长'],[UsersThree,'加入会员群','与同行一起成长']].map(([Icon,title,description])=><div key={title}><Icon size={25} weight="duotone"/><span><b>{title}</b><small>{description}</small></span></div>)}</div></section>
      <section aria-label="官方文章"><div className="oc-toolbar"><div className="oc-categories" aria-label="文章分类">{COMMUNITY_CATEGORIES.map(([id,label])=><button key={id} aria-pressed={category===id} className={category===id?'active':''} onClick={()=>{setCategory(id);setTopic('');}}>{label}</button>)}</div><div className="oc-search-row"><label><MagnifyingGlass size={17}/><input aria-label="搜索官方文章" placeholder="搜索文章、专题…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="文章排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">最新发布</option><option value="recommended">官方推荐</option></select></div></div>
      {topic&&<div className="oc-filter-status">专题：{topic}<button onClick={()=>setTopic('')}>清除筛选 ×</button></div>}
      {loading?<div className="oc-state" role="status">正在加载官方内容…</div>:error?<div className="oc-state" role="alert"><p>{error}</p><button onClick={load}>重新加载</button></div>:filtered.length?<><div className="oc-grid">{filtered.slice(0,limit).map(item=><article className="oc-card" key={item.id}><button className="oc-card-open" onClick={()=>openArticle(item)}><div className={`oc-cover oc-cover-${item.category}`}>{item.coverUrl?<img src={item.coverUrl} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none';}}/>:<div className="oc-cover-fallback"><BookOpenText size={32}/><span>{categoryName(item.category)}</span><strong>{item.title}</strong></div>}<div className="oc-badges">{item.pinned&&<span>置顶</span>}{item.recommended&&<span>推荐</span>}</div></div><div className="oc-card-copy"><div className="oc-byline"><img src="/assets/oneshowlearn-brandmark.png" alt=""/><span>OneShowLearn</span><ShieldCheck size={14}/></div><h2>{item.title}</h2><p>{item.summary||'阅读官方发布的完整内容。'}</p><footer><span><Clock size={14}/>{date(item.publishedAt)}</span><span>{categoryName(item.category)}<ArrowUpRight size={14}/></span></footer></div></button></article>)}</div>{filtered.length>limit&&<button className="oc-load-more" onClick={()=>setLimit(x=>x+12)}>加载更多文章（还有 {filtered.length-limit} 篇）</button>}</>:<div className="oc-state"><Empty title={items.length?'没有找到相关文章':'官方内容即将发布'} action={items.length?'清除筛选':admin?'前往发布文章':undefined} onAction={()=>items.length?(setCategory('all'),setTopic(''),setQuery('')):navigate('/admin/community')}>{items.length?'试试其他关键词或分类。':'这里将持续分享产品开发、上线和增长的实践内容。'}</Empty></div>}
      </section></main><aside className="oc-rail"><GroupCard settings={settings} onOpen={()=>setGroup(true)}/><Panel title="学习动态"><div className="oc-activity"><FileText size={20}/><span>本月发布文章<b>{loading||error?'—':recent} 篇</b></span></div><div className="oc-activity"><BookOpenText size={20}/><span>官方内容收录<b>{loading||error?'—':items.length} 篇</b></span></div><p className="oc-muted">持续分享，和你一起把知识用在实践中。</p></Panel><Panel title="学习专题">{topics.length?topics.map(t=><button className="oc-rail-link" key={t.name} onClick={()=>{setTopic(t.name);setCategory('all');}}><BookOpenText size={21}/><span>{t.name}<small>{t.count} 篇文章</small></span><ArrowRight size={14}/></button>):<p className="oc-muted">专题将在官方文章发布后开放。</p>}</Panel><Panel title="推荐资源" action={<button className="oc-text-link" onClick={()=>navigate('/resources')}>查看全部<ArrowRight size={14}/></button>}>{resources.length?resources.map(r=><button className="oc-rail-link" key={r.id} onClick={()=>setResource(r)}><FileText size={21}/><span>{r.title}<small>课程配套资料 · 按课程权限访问</small></span><ArrowUpRight size={14}/></button>):<p className="oc-muted">精选资料准备中，也可以前往资源中心浏览。</p>}</Panel></aside></div>
    {resource&&<ResourceReader key={resource.id} resource={resource} model={model} navigate={navigate} notify={notify} close={()=>setResource(null)}/>}
    {selected&&<Modal title="官方文章" close={()=>{reading.current++;setSelected(null);}}>{articleLoading?<p className="oc-state" role="status">正在读取文章…</p>:articleError?<div className="oc-state" role="alert">{articleError}<button onClick={()=>openArticle(selected)}>重试</button></div>:<CommunityArticle article={selected}/>}</Modal>}
    {group&&<Modal title={settings.groupTitle} close={()=>setGroup(false)}><div className="oc-group-dialog"><WechatLogo size={40}/><p>{settings.groupDescription}</p>{settings.groupAccessible&&settings.qrUrl?<><img src={settings.qrUrl} alt="官方会员学习群二维码" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true;e.currentTarget.nextElementSibling.textContent='二维码暂时无法加载，请稍后重试或联系官方。';}}/><p>{settings.groupInstructions||COMMUNITY_SETTINGS.groupInstructions}</p>{settings.groupExpiresAt&&<small>二维码有效至 {settings.groupExpiresAt}（北京时间）</small>}</>:<p>{settings.groupExpired?'二维码已到期，官方正在更新入群方式，请稍后再来。':settings.groupReady?'该群面向拥有有效课程权益的学员。请使用购买课程的账号登录；如仍无法查看，请联系官方核对权益。':'官方正在准备入群方式，配置完成后会在这里展示。'}</p>}{admin&&<button className="ps-primary" onClick={()=>navigate('/admin/community')}>管理会员群配置<ArrowRight size={16}/></button>}</div></Modal>}
  </div>;
}
