import {useEffect,useState} from 'react';
import {ArrowRight,BookOpenText,CaretRight,FileText,List,MagnifyingGlass,SquaresFour,Star} from '@phosphor-icons/react';
import {api} from './api.js';
import {courseArt} from './Workspace.jsx';
import {ResourceReader} from './ResourceCenter.jsx';
import {resourceArt,resourceCategory,resourceTags} from './resource-model.js';
import {Empty,Gate,Markdown,Modal,Panel,PersonalHeading,Promo,TagCloud} from './PersonalShared.jsx';
import {liveNotes,matchText,shortDate,tagCounts} from './personal-model.js';
import prd from './assets/resources-prd-v1.webp';
import code from './assets/resources-code-v1.webp';
import payment from './assets/resources-payment-v1.webp';
import deploy from './assets/resources-deploy-v1.webp';
const cover={prd,code,payment,deploy};
const categories=[['all','全部'],['course','课程与项目'],['note','笔记'],['resource','资源'],['article','文章'],['tool','工具']];
export function FavoritesWorkspace({model,navigate,notify,query,setQuery}){
 const [resources,setResources]=useState([]),[error,setError]=useState(''),[category,setCategory]=useState('all'),[tag,setTag]=useState(''),[sort,setSort]=useState('recent'),[view,setView]=useState('grid'),[modal,setModal]=useState(null),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;api('/resources').then(d=>active&&setResources(d.items||[])).catch(e=>active&&setError(e.message));return()=>{active=false;};},[retry,model.user?.id]);
 const packs=[...new Map([...model.library,...model.recommendations].map(p=>[p.id,p])).values()];
 const favorites=[...model.state.favorites].reverse().map((id,index)=>{const p=packs.find(p=>p.id===id);return p?{id:`pack-${id}`,source:p,kind:'course',title:p.title,description:p.subtitle,tags:[p.path_title||'实战课程'],date:null,order:index,image:courseArt(p)}:null;}).filter(Boolean);
 for(const saved of model.state.resourceFavorites||[]){const r=resources.find(r=>r.id===saved.id);if(r)favorites.push({id:`resource-${r.id}`,source:r,kind:resourceCategory(r)==='tools'?'tool':r.type==='document'?'article':'resource',title:r.title,description:r.summary,tags:resourceTags(r),date:saved.savedAt,image:cover[resourceArt(r)]});}
 for(const n of liveNotes(model.state).filter(n=>n.starred))favorites.push({id:`note-${n.id}`,source:n,kind:'note',title:n.title,description:n.body.replace(/[#>`*]/g,'').slice(0,100),tags:n.tags||[],date:n.updatedAt,image:prd});
 const visible=favorites.filter(f=>(category==='all'||f.kind===category)&&(!tag||f.tags.includes(tag))&&matchText(f,query)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh-CN'):(new Date(b.date||0)-new Date(a.date||0))||(a.order||0)-(b.order||0));
 const open=item=>item.kind==='course'?navigate(`/packs/${item.source.slug}`):setModal(item);
 const remove=async item=>{let state={...model.state};if(item.kind==='course')state.favorites=state.favorites.filter(id=>id!==item.source.id);else if(item.kind==='note')state.notes=state.notes.map(n=>n.id===item.source.id?{...n,starred:false}:n);else state.resourceFavorites=(state.resourceFavorites||[]).filter(r=>r.id!==item.source.id);if(await model.saveState(state))notify('已取消收藏，原内容仍然保留');};
 return <div className="ps-layout"><div className="ps-main"><PersonalHeading title="我的收藏" subtitle="收藏你感兴趣的课程、文章、资源和笔记，随时回顾，持续学习。" quote="收藏的是知识，更是未来的可能性。" navigate={navigate}/><Gate model={model} navigate={navigate}><div className="ps-catalog-toolbar"><div className="ps-tabs">{categories.map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>{setCategory(id);setTag('');}}>{label} ({id==='all'?favorites.length:favorites.filter(f=>f.kind===id).length})</button>)}</div><div><select aria-label="收藏排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">最近收藏</option><option value="title">按名称</option></select><span className="ps-view-switch"><button aria-label="网格视图" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><SquaresFour size={18}/></button><button aria-label="列表视图" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={19}/></button></span></div></div>{(tag||query)&&<div className="ps-filter-label">{tag&&`标签：${tag} `}{query&&`搜索：${query}`}<button onClick={()=>{setTag('');setQuery('');}}>清除筛选</button></div>}{error&&<p className="ps-alert">资源收藏暂时无法读取。<button onClick={()=>{setError('');setRetry(v=>v+1);}}>重试</button></p>}
 {visible.length?<div className={`fv-grid ${view==='list'?'fv-list':''}`}>{visible.map(item=><article className="fv-card" key={item.id}><div className="fv-art"><button onClick={()=>open(item)} aria-label={`打开${item.title}`}><img src={item.image} alt=""/><small>分类示意</small></button><button className="fv-star" disabled={model.busy} aria-label={`取消收藏${item.title}`} title="取消收藏" onClick={()=>remove(item)}><Star size={20} weight="fill"/></button></div><div className="fv-body"><span className={`ps-label ps-kind-${item.kind}`}>{categories.find(c=>c[0]===item.kind)?.[1]}</span><button className="fv-title" onClick={()=>open(item)}><h2>{item.title}</h2></button><p>{item.description||'打开内容，继续你的学习与实践。'}</p><div className="ps-inline-tags">{item.tags.slice(0,3).map(t=><button key={t} onClick={()=>setTag(t)}>{t}</button>)}</div><footer><span>{item.date?`${item.kind==='note'?'更新于':'收藏于'} ${shortDate(item.date)}`:'已收藏 · 时间未记录'}</span><button className="ps-icon" aria-label={`查看${item.title}`} onClick={()=>open(item)}><ArrowRight size={16}/></button></footer></div></article>)}</div>:<Empty title={favorites.length?'没有找到匹配的收藏':'把值得再看的内容，收藏在这里'} action={favorites.length?'重置筛选':'探索学习资源'} onAction={()=>favorites.length?(setCategory('all'),setTag(''),setQuery('')):navigate('/resources')} Icon={Star}>在课程、资源详情或笔记中点一下收藏，就能在这里找到。</Empty>}</Gate></div><aside className="ps-rail"><Panel title="收藏统计"><div className="fv-total"><strong>{favorites.length}</strong><small>当前可见收藏</small></div><div className="fv-kind-stats">{categories.slice(1).map(([id,label],i)=><button key={id} onClick={()=>setCategory(id)}><span className={`ps-tile ps-tone-${i%4}`}><FileText size={19}/></span><small>{label}</small><b>{favorites.filter(f=>f.kind===id).length}</b></button>)}</div></Panel><Panel title="标签云"><TagCloud tags={tagCounts(favorites).slice(0,12)} selected={tag} onClick={t=>setTag(tag===t?'':t)}/></Panel><Panel title="最近收藏" action={<button className="ps-text" onClick={()=>{setCategory('all');setTag('');setSort('recent');}}>查看全部<ArrowRight size={13}/></button>}><div className="fv-recent">{[...favorites].sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,5).map((item,i)=><button key={item.id} onClick={()=>open(item)}><b>{i+1}</b><span><strong>{item.title}</strong><small>{item.date?shortDate(item.date):'课程与项目收藏'}</small></span></button>)}{!favorites.length&&<p className="ps-muted">暂无收藏记录，从感兴趣的内容开始。</p>}</div></Panel><Promo kind="favorites" onClick={()=>navigate('/resources')}/></aside>
 {modal?.kind==='note'&&<Modal title={modal.title} close={()=>setModal(null)}><div className="ps-modal-body"><Markdown body={modal.source.body}/><button className="ps-primary" onClick={()=>navigate('/notes')}>进入学习笔记<ArrowRight size={15}/></button></div></Modal>}
 {modal&&modal.kind!=='note'&&<ResourceReader resource={modal.source} model={model} navigate={navigate} notify={notify} close={()=>setModal(null)}/>}
 </div>;
}
