import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Code,FileText,ListBullets,MagnifyingGlass,Microphone,NotePencil,Plus,Quotes,Robot,Star,TextB,TextH,Trash,UploadSimple} from '@phosphor-icons/react';
import {DownloadText,Empty,Gate,Markdown,Modal,Panel,PersonalHeading,Promo,RecentCourses,TagCloud} from './PersonalShared.jsx';
import {liveNotes,matchText,monthCount,shortDate,tagCounts,tagsFromText} from './personal-model.js';
import {LearningNotesLibrary} from './LearningNotesLibrary.jsx';

export function NotesWorkspace(props){const [source,setSource]=useState('personal');const switchTo=value=>{const change=()=>setSource(value);if(window.dispatchEvent(new Event('oneshowlearn:before-navigate',{cancelable:true}))&&(!props.guard.current||props.guard.current(change)))change();};return <><div className="ls-tabs ls-note-source"><button aria-pressed={source==='personal'} onClick={()=>switchTo('personal')}>个人笔记</button><button aria-pressed={source==='learning'} onClick={()=>switchTo('learning')}>课程 / 项目笔记</button></div>{source==='personal'?<PersonalNotesWorkspace {...props}/>:<LearningNotesLibrary {...props}/>}</>;}
function PersonalNotesWorkspace({model,navigate,notify,query,setQuery,guard}){
 const [selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[editing,setEditing]=useState(false),[tab,setTab]=useState('all'),[tag,setTag]=useState(''),[sort,setSort]=useState('modified'),[error,setError]=useState('');
 const bodyRef=useRef(null),importRef=useRef(null),editorRef=useRef(null);
 const [pending,setPending]=useState(null);
 const notes=liveNotes(model.state),trash=(model.state.notes||[]).filter(n=>n.deletedAt);
 const current=(model.state.notes||[]).find(n=>n.id===selected)||null;
 const dirty=Boolean(draft&&(draft.title!==(current?.title||'')||draft.body!==(current?.body||'')||draft.tagsText!==(current?.tags||[]).join(', ')));
 const confirmLeave=proceed=>{if(!dirty)return true;setPending(()=>proceed);return false;};
 useEffect(()=>{guard.current=confirmLeave;const prevent=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>{guard.current=null;window.removeEventListener('beforeunload',prevent);};},[dirty]);
 useEffect(()=>{if(!selected&&!draft&&notes.length)setSelected(notes[0].id);},[model.state.notes]);
 const open=(note,write=false)=>{const apply=()=>{setSelected(note?.id||null);setDraft(write?{title:note?.title||'',body:note?.body||'',tagsText:(note?.tags||[]).join(', ')}:null);setEditing(write);setError('');editorRef.current?.scrollIntoView({behavior:'smooth',block:'start'});};if(confirmLeave(apply))apply();};
 const newNote=()=>{if(!model.user)return navigate('/login');setTab('all');open(null,true);};
 const save=async()=>{
   if(!draft?.title.trim()){setError('请填写笔记标题。');return;}
   const now=new Date().toISOString(),id=selected||crypto.randomUUID();
   const note={...current,id,title:draft.title.trim(),body:draft.body,tags:tagsFromText(draft.tagsText),...(current?{}:{createdAt:now}),updatedAt:now};
   if(await model.saveState({...model.state,notes:[note,...model.state.notes.filter(n=>n.id!==id)]})){setSelected(id);setDraft(null);setEditing(false);setError('');notify('笔记已保存到你的账号');}else setError('保存未成功，修改已保留，请重试。');
 };
 const patch=async(change)=>{if(!current)return;if(await model.saveState({...model.state,notes:model.state.notes.map(n=>n.id===current.id?{...n,...change,updatedAt:new Date().toISOString()}:n)}))notify(change.deletedAt?'笔记已移入回收站，可以恢复':change.deletedAt===null?'笔记已恢复':'笔记已更新');};
 const insert=(prefix,suffix='')=>{const area=bodyRef.current,start=area?.selectionStart||0,end=area?.selectionEnd||start;setDraft(d=>({...d,body:d.body.slice(0,start)+prefix+d.body.slice(start,end)+suffix+d.body.slice(end)}));area?.focus();};
 const importText=async(e)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>80000){notify('请导入小于 80 KB 的文本文件');return;}const body=await file.text();if(body.length>20000){notify('单篇笔记最多 20,000 字');return;}const apply=()=>{setSelected(null);setDraft({title:file.name.replace(/\.(txt|md)$/i,''),body,tagsText:''});setEditing(true);setTab('all');};if(confirmLeave(apply))apply();};
 const source=tab==='trash'?trash:notes;
 const visible=source.filter(n=>matchText(n,query)&&(!tag||(n.tags||[]).includes(tag))).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh-CN'):new Date(b.updatedAt)-new Date(a.updatedAt));
 return <div className="ps-layout ps-notes-layout"><div className="ps-main"><PersonalHeading title="学习笔记" subtitle="记录学习过程中的思考、灵感和知识，让每一次学习都有沉淀。" quote="好记性不如烂笔头，更好的笔记成就更好的你。" navigate={navigate}/><Gate model={model} navigate={navigate}><div className="nt-workspace"><section className="nt-list"><div className="ps-tabs nt-tabs">{[['all','全部笔记'],['tags','我的标签'],['trash','回收站']].map(([id,title])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setTag('');}}>{title}</button>)}</div><div className="nt-search"><label className="ps-search"><MagnifyingGlass size={16}/><input aria-label="搜索笔记" placeholder="搜索笔记…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="笔记排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="modified">最新修改</option><option value="title">按名称</option></select></div>{tab==='tags'&&<TagCloud tags={tagCounts(notes)} selected={tag} onClick={t=>setTag(tag===t?'':t)}/>}
 <div className="nt-note-list">{visible.map((note,index)=><button className={`nt-note ${selected===note.id?'selected':''}`} key={note.id} onClick={()=>open(note)}><span className={`ps-tile ps-tone-${index%4}`}><FileText size={23}/></span><span><strong>{note.title}</strong><p>{note.body.replace(/[#*>`]/g,'').slice(0,90)||'暂无正文'}</p><span className="nt-note-meta"><span>{(note.tags||[]).slice(0,2).map(t=><i key={t}>{t}</i>)}</span><small>{shortDate(note.updatedAt)}</small></span></span></button>)}{!visible.length&&<div className="nt-list-empty">{tab==='trash'?'回收站是空的':query||tag?'没有找到匹配的笔记':'还没有笔记，记下第一个想法吧。'}</div>}</div><button className="nt-new" onClick={newNote}><Plus size={16}/>新建笔记</button></section>
 <section className="nt-editor" ref={editorRef}><header className="nt-toolbar"><div>{editing?<>{[[TextH,'标题','## '],[TextB,'加粗','**','**'],[ListBullets,'任务清单','- [ ] '],[Code,'代码块','\n```\n','\n```'],[Quotes,'引用','> ']].map(([Icon,label,prefix,suffix])=><button type="button" title={label} aria-label={label} key={label} onClick={()=>insert(prefix,suffix)}><Icon size={17}/></button>)}</>:<span>阅读视图</span>}</div><div>{current&&!current.deletedAt&&!editing&&<button className="ps-icon" aria-label={current.starred?'取消收藏笔记':'收藏笔记'} disabled={model.busy} onClick={()=>patch({starred:!current.starred})}><Star size={17} weight={current.starred?'fill':'regular'}/></button>}<small>{editing?dirty?'尚未保存':'编辑中':current?`更新于 ${shortDate(current.updatedAt)}`:'私人学习空间'}</small>{editing&&<button className="nt-save" disabled={model.busy} onClick={save}><Check size={16}/>{model.busy?'保存中':'保存'}</button>}{!editing&&current&&!current.deletedAt&&<button className="ps-text" onClick={()=>open(current,true)}>编辑</button>}</div></header>
 {editing&&draft?<div className="nt-writing"><input className="nt-title-input" aria-label="笔记标题" placeholder="给这个想法起个标题" maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><label className="nt-tag-input">标签<input aria-label="笔记标签" placeholder="用逗号分隔，例如 AI 开发, Codex" value={draft.tagsText} onChange={e=>setDraft({...draft,tagsText:e.target.value})} maxLength={200}/></label><textarea ref={bodyRef} aria-label="笔记正文" maxLength={20000} placeholder="记录你的关键结论、实践过程与下一步行动…支持 Markdown。" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/><small>{draft.body.length} / 20,000 字 · 手动保存</small>{error&&<p className="ps-alert" role="alert">{error}</p>}<footer><button className="ps-outline" onClick={()=>open(current)}>取消</button><button className="ps-primary" disabled={model.busy} onClick={save}><Check size={16}/>{model.busy?'正在保存':'保存笔记'}</button></footer></div>:current?<article className="nt-reading"><h2>{current.title}</h2><div className="ps-inline-tags">{(current.tags||[]).map(t=><button key={t} onClick={()=>{setTab('tags');setTag(t);}}>{t}</button>)}</div>{current.deletedAt&&<div className="ps-notice">这篇笔记在回收站中，不会显示在收藏夹。<button className="ps-text" disabled={model.busy} onClick={()=>patch({deletedAt:null})}>恢复笔记</button></div>}<Markdown body={current.body||'开始编辑，写下你的第一条记录。'} onCheck={!current.deletedAt&&!model.busy?line=>{const lines=current.body.split('\n');lines[line]=lines[line].replace(/\[([ xX])\]/,(_,v)=>v===' '?'[x]':'[ ]');patch({body:lines.join('\n')});}:undefined}/><footer><DownloadText title={current.title} body={current.body}/>{!current.deletedAt&&<button className="ps-text" disabled={model.busy} onClick={()=>patch({deletedAt:new Date().toISOString()})}><Trash size={15}/>移入回收站</button>}</footer></article>:<Empty title="每一个想法，都值得记录" action="写第一篇笔记" onAction={newNote} Icon={NotePencil}>从关键结论、一个问题或一段 Prompt 开始。</Empty>}
 </section></div></Gate></div><aside className="ps-rail"><Panel title="笔记统计"><div className="ps-note-stats">{[[notes.length,'笔记总数'],[monthCount(notes),'本月新增'],[notes.filter(n=>n.starred).length,'收藏笔记'],[tagCounts(notes).length,'常用标签']].map(([v,label])=><div key={label}><strong>{model.loading?'—':v}</strong><small>{label}</small></div>)}</div></Panel><Panel title="常用标签" action={<button className="ps-text" onClick={()=>{setTab('tags');setTag('');}}>查看标签</button>}><TagCloud tags={tagCounts(notes).slice(0,12)} selected={tag} onClick={t=>{setTab('tags');setTag(t);}}/></Panel><Panel title="快速记录"><div className="nt-quick"><button onClick={newNote}><NotePencil size={21}/>新建笔记</button><button disabled title="此处独立笔记整理暂未开放；课程和项目笔记请在课时右侧使用 AI 整理"><Robot size={21}/>独立笔记 AI · 待开放</button><button disabled title="语音转写尚未接入"><Microphone size={21}/>语音记录 · 待开放</button><button onClick={()=>model.user?importRef.current?.click():navigate('/login')}><UploadSimple size={21}/>导入文本</button><input ref={importRef} type="file" hidden accept=".md,.txt,text/plain,text/markdown" onChange={importText}/></div><small className="ps-muted">支持 .md / .txt；导入后点击保存。</small></Panel><RecentCourses model={model} navigate={navigate}/><Promo kind="notes" onClick={newNote}/></aside>{pending&&<Modal title="保留未保存的修改？" close={()=>setPending(null)}><div className="ps-modal-body"><p>这篇笔记有尚未保存的内容。离开前可以继续编辑并保存。</p><div className="ps-form-actions"><button className="ps-outline" onClick={()=>setPending(null)}>继续编辑</button><button className="ps-primary" onClick={()=>{const proceed=pending;setPending(null);proceed();}}>放弃修改</button></div></div></Modal>}</div>;
}
