import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CaretRight,FileText,FolderSimple,Plus,X} from '@phosphor-icons/react';
import {courseArt} from './Workspace.jsx';
import notesPoster from './assets/notes-promo-v1.webp';
import favoritePoster from './assets/favorites-promo-v1.webp';
import achievementPoster from './assets/achievements-promo-v1.webp';
import {safeResourceUrl} from './opc-model.js';

export function PersonalHeading({title,subtitle,quote,navigate,action}){return <header className="ps-heading"><nav aria-label="当前位置"><button onClick={()=>navigate('/app')}>工作台</button><CaretRight size={13}/><span>{title}</span></nav><div><section><h1>{title}</h1><p>{subtitle}</p></section>{quote&&<blockquote>“{quote}”<span>— OneShowLearn</span></blockquote>}{action}</div></header>;}
export function Panel({title,action,children,className=''}){return <section className={`ps-panel ${className}`}><header><h2>{title}</h2>{action}</header>{children}</section>;}
export function Empty({title,children,action,onAction,Icon=FolderSimple}){return <div className="ps-empty"><Icon size={34} weight="duotone"/><h3>{title}</h3><p>{children}</p>{action&&<button className="ps-primary" onClick={onAction}>{action}<ArrowRight size={15}/></button>}</div>;}
export function Gate({model,navigate,children}){return model.loading&&!model.user?<Empty title="正在读取你的学习空间…"/>:!model.user?<Empty title="登录后保存你的学习记录" action="登录学习账号" onAction={()=>navigate('/login')}>笔记、收藏和成果仅对自己的账号可见。</Empty>:children;}
export function Modal({title,close,children,confirmClose=false,titleId='ps-modal-title',className=''}){const ref=useRef(null);const [confirming,setConfirming]=useState(false);const requestClose=()=>confirmClose?setConfirming(true):close();useEffect(()=>{const dialog=ref.current;dialog.showModal();return()=>dialog.close();},[]);return <dialog className={`ps-modal ${className}`.trim()} ref={ref} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();requestClose();}} onClick={e=>e.target===e.currentTarget&&requestClose()}><header><h2 id={titleId}>{title}</h2><button className="ps-icon" aria-label="关闭窗口" onClick={requestClose}><X size={20}/></button></header>{confirming?<div className="ps-modal-body"><p>有尚未保存的内容，确认放弃本次修改吗？</p><div className="ps-form-actions"><button className="ps-outline" onClick={()=>setConfirming(false)}>继续编辑</button><button className="ps-primary" onClick={close}>放弃修改</button></div></div>:children}</dialog>;}
export function TagCloud({tags,onClick,selected}){return <div className="ps-tag-cloud">{tags.map(([tag,count])=><button key={tag} aria-pressed={selected===tag} onClick={()=>onClick(tag)}>{tag}<span>{count}</span></button>)}{!tags.length&&<p className="ps-muted">添加内容后，你的标签会显示在这里。</p>}</div>;}
export function Promo({kind,onClick}){const content={notes:['让记录成为','你成长的加速器','沉淀实践经验','随时回顾复习','立即记录',notesPoster],favorites:['收藏好内容','随时回顾，高效学习','按类别快速查找','让学习更有条理','探索更多',favoritePoster],achievements:['分享你的成果','让进步被自己看见','记录项目与作品','留下每一步实践','新建成果',achievementPoster]}[kind];return <section className={`ps-promo ps-promo-${kind}`}><img src={content[5]} alt=""/><div><h2>{content[0]}<br/>{content[1]}</h2><p>{content[2]}<br/>{content[3]}</p><button onClick={onClick}>{content[4]}<ArrowRight size={14}/></button></div></section>;}
export function RecentCourses({model,navigate}){const packs=model.library.filter(p=>p.startedCount>0).sort((a,b)=>Number(b.id===model.recent?.id)-Number(a.id===model.recent?.id)).slice(0,3);return <Panel title="最近学习的课程" action={<button className="ps-text" onClick={()=>navigate('/courses')}>查看全部<ArrowRight size={13}/></button>}><div className="ps-recent-courses">{packs.map(pack=><button key={pack.id} onClick={()=>navigate(`/packs/${pack.slug}`)}><img src={courseArt(pack)} alt=""/><span><strong>{pack.title}</strong><small>已学习 {pack.completedCount||0} / {pack.contentCount||0} 项内容</small></span><CaretRight size={13}/></button>)}{!packs.length&&<p className="ps-muted">开始课程后，这里会记录你的学习足迹。</p>}</div></Panel>;}
export function DownloadText({title,body,label='导出 Markdown'}){const [urlRef]=[useRef('')];const anchor=useRef(null);useEffect(()=>{const url=URL.createObjectURL(new Blob([`# ${title}\n\n${body}`],{type:'text/markdown;charset=utf-8'}));urlRef.current=url;if(anchor.current)anchor.current.href=url;return()=>URL.revokeObjectURL(url);},[title,body]);return <a ref={anchor} className="ps-text" download={`${title.replace(/[\\/:*?"<>|]/g,'-').slice(0,90)||'学习笔记'}.md`}>{label}<ArrowRight size={13}/></a>;}
function Inline({text}){return String(text).split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part,i)=>part.startsWith('**')?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith('`')?<code key={i}>{part.slice(1,-1)}</code>:part);}
export function Markdown({body,onCheck}){const blocks=String(body||'').split('\n');const elements=[];let code=[];let inCode=false;for(let i=0;i<blocks.length;i++){const line=blocks[i];if(line.startsWith('```')){if(inCode){elements.push(<pre key={`code-${i}`}><code>{code.join('\n')}</code></pre>);code=[];}inCode=!inCode;continue;}if(inCode){code.push(line);continue;}const check=line.match(/^\s*[-*] \[([ xX])\] (.*)/);if(check){elements.push(<label className="ps-markdown-check" key={i}><input type="checkbox" checked={check[1].toLowerCase()==='x'} disabled={!onCheck} onChange={()=>onCheck(i)}/><Inline text={check[2]}/></label>);continue;}if(/^#{1,6} /.test(line)){const text=line.replace(/^#{1,6} /,'');elements.push(<h3 key={i}><Inline text={text}/></h3>);}else if(line.startsWith('> '))elements.push(<blockquote key={i}><Inline text={line.slice(2)}/></blockquote>);else if(/^[-*] /.test(line))elements.push(<p className="ps-markdown-bullet" key={i}><Inline text={`• ${line.slice(2)}`}/></p>);else if(line.trim())elements.push(<p key={i}><Inline text={line}/></p>);}if(code.length)elements.push(<pre key="last-code"><code>{code.join('\n')}</code></pre>);return <div className="ps-markdown">{elements}</div>;}
export function SafeLink({url,children}){const href=safeResourceUrl(url);return href?<a href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowRight size={14}/></a>:null;}
