import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ChatCircleDots,CheckCircle,ShieldCheck,Receipt} from '@phosphor-icons/react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {api,money} from './api.js';
import {BrandIdentity} from './BrandIdentity.jsx';
import {Gate} from './PersonalShared.jsx';
import {SUPPORT_CATEGORIES,SUPPORT_STATES} from '../server/service-definition.mjs';
import './service-center.css';

export function ServiceLinks({compact=false}){return <nav className={`service-links${compact?' is-compact':''}`} aria-label="协议与服务"><a href="/legal/terms" target="_blank" rel="noopener noreferrer">用户协议</a><a href="/legal/privacy" target="_blank" rel="noopener noreferrer">隐私说明</a><a href="/legal/purchase" target="_blank" rel="noopener noreferrer">购买说明</a><a href="/support" target="_blank" rel="noopener noreferrer">帮助与售后</a></nav>;}
export function useService(){const [data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;api('/service/public').then(d=>{if(active){setData(d);setError('');}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[retry]);return {data,error,reload:()=>setRetry(x=>x+1)};}
function Markdown({children}){return <div className="service-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{img:()=>null,a:({href,children})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>}}>{children}</ReactMarkdown></div>;}
export function ServiceSummary(){const {data,error,reload}=useService();return <section className="service-summary" aria-label="购买与服务范围"><header><ShieldCheck size={21}/><h3>购买与服务说明</h3></header>{error?<p role="alert">说明暂未加载。<button onClick={reload}>重试</button></p>:!data?<p role="status">正在读取服务范围…</p>:<>{[['所购课程','courseScope'],['实战项目','projectScope'],['AI 学习支持','aiScope'],['社群与更新','communityScope'],['课程更新','updateScope'],['售后申请','refundPolicy']].map(([title,key])=><details key={key}><summary>{title}</summary><p>{data.settings[key]}</p></details>)}{data.settings.responseTime&&<p className="service-small">通常回复：{data.settings.responseTime}</p>}</>}<ServiceLinks compact/></section>;}
export function LegalPage({kind,navigate}){const {data,error,reload}=useService();const key={terms:'termsBody',privacy:'privacyBody',purchase:'purchaseBody'}[kind];return <main className="legal-page"><header><button onClick={()=>navigate('/')} aria-label="返回 OneShowLearn 官网"><BrandIdentity/></button><button onClick={()=>navigate('/course-offer')}>查看课程<ArrowRight size={16}/></button></header><article><button className="service-back" onClick={()=>navigate('/')}><ArrowLeft size={16}/>返回首页</button>{error?<p role="alert">{error}<button onClick={reload}>重新加载</button></p>:!data?<p role="status">正在读取说明…</p>:<><Markdown>{data.settings[key]||'本说明暂未补充，请通过帮助与售后联系官方确认。'}</Markdown><div className="service-contact"><h2>联系与支持</h2>{data.settings.operatorName&&<p>运营主体：{data.settings.operatorName}</p>}{data.settings.contactEmail&&<p>邮箱：<a href={`mailto:${data.settings.contactEmail}`}>{data.settings.contactEmail}</a></p>}{data.settings.contactWechat&&<p>官方微信：{data.settings.contactWechat}</p>}<p>站内申请入口：<button onClick={()=>navigate('/support')}>帮助与售后<ArrowRight size={15}/></button></p>{data.updatedAt&&<small>说明更新于 {data.updatedAt} · 版本 {data.version.slice(0,8)}</small>}</div></>}<ServiceLinks/></article></main>;}
function useDraftGuard(dirty,busy){useEffect(()=>{const guard=e=>{if(dirty||busy){e.preventDefault();window.alert(busy?'正在提交，请稍候。':'你有未提交的输入，请先提交或清空后再离开。');}};const unload=e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('oneshowlearn:before-navigate',guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('oneshowlearn:before-navigate',guard);window.removeEventListener('beforeunload',unload);};},[dirty,busy]);}
const time=value=>new Date(value.replace(' ','T')+(value.includes('Z')?'':'Z')).toLocaleString('zh-CN');
const label=(list,key)=>list.find(x=>x[0]===key)?.[1]||key;
function Messages({item}){return <div className="support-messages">{item.messages.map(m=><article className={m.authorType==='admin'?'is-official':''} key={m.id}><header><strong>{m.authorType==='admin'?'官方回复':'你的说明'}</strong><time>{time(m.createdAt)}</time></header><p>{m.message}</p></article>)}</div>;}
export function SupportCenter({model,navigate}){return <div className="support-page"><header className="support-heading"><span>WE ARE HERE TO HELP</span><h1>帮助与售后</h1><p>购买、学习或账号问题，留下说明，我们一起处理。</p></header><Gate model={model} navigate={navigate}><SupportWorkspace key={model.user?.id}/></Gate></div>;}
function SupportWorkspace(){
  const [items,setItems]=useState(null),[orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reply,setReply]=useState('');
  const [draft,setDraft]=useState({category:'purchase',title:'',orderId:'',message:''});const key=useRef(crypto.randomUUID()),replyKey=useRef(crypto.randomUUID()),sending=useRef(false);
  const {data:service}=useService();useDraftGuard(Boolean(draft.title||draft.message||reply),busy);
  const load=async()=>{try{const [r,o]=await Promise.all([api('/support/requests'),api('/support/orders')]);setItems(r.items);setOrders(o.items);setSelected(old=>old?r.items.find(x=>x.id===old.id)||old:null);setError('');}catch(e){setError(e.message);}};
  useEffect(()=>{load();},[]);
  const submit=async e=>{e.preventDefault();if(sending.current)return;sending.current=true;setBusy(true);setError('');setMessage('');try{const result=await api('/support/requests',{method:'POST',body:JSON.stringify({...draft,orderId:draft.orderId?Number(draft.orderId):null,requestKey:key.current})});setSelected(result.item);setDraft({category:'purchase',title:'',orderId:'',message:''});key.current=crypto.randomUUID();setMessage('申请已提交。管理员将人工核实并在此回复；未发起扣款或退款。');await load();}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}};
  const sendReply=async e=>{e.preventDefault();if(sending.current||!reply.trim())return;sending.current=true;setBusy(true);setError('');try{const r=await api(`/support/requests/${selected.id}/replies`,{method:'POST',headers:{'If-Match':selected.version},body:JSON.stringify({message:reply,requestKey:replyKey.current})});setSelected(r.item);setReply('');replyKey.current=crypto.randomUUID();await load();}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}};
  const change=(field,value)=>{setDraft(v=>({...v,[field]:value}));key.current=crypto.randomUUID();};
  return <div className="support-layout"><section className="support-panel"><header><ChatCircleDots size={24}/><div><h2>提交问题</h2><p>所有申请仅你和管理员可见。</p></div></header>{service&&<div className="support-contact">{service.settings.contactEmail&&<a href={`mailto:${service.settings.contactEmail}`}>{service.settings.contactEmail}</a>}{service.settings.contactWechat&&<span>官方微信：{service.settings.contactWechat}</span>}{service.settings.responseTime&&<span>通常回复：{service.settings.responseTime}</span>}</div>}<form onSubmit={submit}><fieldset disabled={busy}><label>问题类别<select value={draft.category} onChange={e=>change('category',e.target.value)}>{SUPPORT_CATEGORIES.map(([id,text])=><option key={id} value={id}>{text}</option>)}</select></label><label>关联订单{draft.category==='refund'?'（必选已付款订单）':'（可选）'}<select required={draft.category==='refund'} value={draft.orderId} onChange={e=>change('orderId',e.target.value)}><option value="">选择当前账号的订单</option>{orders.filter(o=>draft.category!=='refund'||o.status==='paid').map(o=><option key={o.id} value={o.id}>{o.orderNo} · {money(o.amountCents)} · {o.status==='paid'?'已支付':o.status==='pending'?'待支付':'已关闭'}</option>)}</select></label><label>问题标题<input required minLength={3} maxLength={120} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="例如：付款后课程还未开通"/></label><label>详细说明<textarea required minLength={10} maxLength={4000} rows={5} value={draft.message} onChange={e=>change('message',e.target.value)} placeholder="说明遇到的情况和发生时间。不要填写验证码、支付密码或密钥。"/></label><p className="service-small">退款申请由管理员人工核实，提交不代表审批通过或款项退回。最近 100 笔订单可在此关联。</p><div className="support-actions"><button type="button" onClick={()=>{setDraft({category:'purchase',title:'',orderId:'',message:''});key.current=crypto.randomUUID();}}>清空输入</button><button className="service-primary">{busy?'正在提交…':'提交申请'}<ArrowRight size={16}/></button></div></fieldset></form>{message&&<p className="service-success" role="status"><CheckCircle size={18}/>{message}</p>}{error&&<p className="service-error" role="alert">{error}<button disabled={busy} onClick={load}>重新载入申请</button></p>}<ServiceLinks compact/></section>
    <section className="support-panel"><header><Receipt size={23}/><div><h2>我的申请</h2><p>最近 100 条申请与官方回复。</p></div><button disabled={busy} onClick={load}>刷新</button></header>{items===null?<p role="status">正在读取申请…</p>:!items.length?<div className="support-empty">还没有申请。遇到问题时，可在左侧留下说明。</div>:<><div className="support-list">{items.map(item=><button disabled={busy} aria-pressed={selected?.id===item.id} key={item.id} onClick={()=>{if(reply.trim()&&!window.confirm('切换申请将清空尚未发送的补充说明，是否继续？'))return;setSelected(item);setReply('');replyKey.current=crypto.randomUUID();}}><span><b>{item.title}</b><small>#{item.id} · {label(SUPPORT_CATEGORIES,item.category)}</small></span><em>{label(SUPPORT_STATES,item.status)}</em></button>)}</div>{selected&&<div className="support-detail"><h3>{selected.title}</h3>{selected.order&&<p className="service-small">关联订单：{selected.order.orderNo} · {money(selected.order.amountCents)}</p>}<Messages item={selected}/><form onSubmit={sendReply}><label>补充说明<textarea rows={3} maxLength={4000} required value={reply} onChange={e=>{setReply(e.target.value);replyKey.current=crypto.randomUUID();}}/></label><div className="support-actions"><button disabled={busy} type="button" onClick={()=>setReply('')}>清空</button><button className="service-primary" disabled={busy||!reply.trim()}>发送补充说明</button></div></form></div>}</>}</section></div>;
}
const fields=[['operatorName','运营主体'],['contactEmail','客服邮箱'],['contactWechat','官方微信'],['responseTime','通常回复时间（不填则不作时效承诺）'],['courseScope','课程购买范围'],['projectScope','独立项目范围'],['aiScope','AI 使用范围'],['communityScope','会员群加入说明'],['updateScope','课程更新范围'],['refundPolicy','退款申请及处理规则'],['termsBody','用户协议正文'],['privacyBody','隐私说明正文'],['purchaseBody','购买说明正文']];
export function AdminService(){
  const [data,setData]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState('contact');const sending=useRef(false);
  const dirty=Boolean(data&&draft&&JSON.stringify(data.draft)!==JSON.stringify(draft));useDraftGuard(dirty,busy);
  const load=async()=>{try{const d=await api('/admin/service');setData(d);setDraft(d.draft);setError('');}catch(e){setError(e.message);}};useEffect(()=>{load();},[]);
  const save=async()=>{if(sending.current)return;sending.current=true;setBusy(true);setError('');try{const r=await api('/admin/service',{method:'PUT',headers:{'If-Match':data.version},body:JSON.stringify(draft)});setData(v=>({...v,version:r.version,draft}));setNotice('草稿已保存，前台仍使用此前发布的说明。');}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}};
  const publish=async()=>{if(dirty||sending.current)return;if(!window.confirm('确认发布这些服务说明？请核实主体、联系方式和售后规则。本操作不会修改价格、支付配置或课程权益。'))return;sending.current=true;setBusy(true);setError('');try{await api('/admin/service/publish',{method:'POST',headers:{'If-Match':data.version},body:'{}'});await load();setNotice('服务说明已发布。');}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}};
  const visible=section==='contact'?fields.slice(0,4):section==='scope'?fields.slice(4,10):fields.slice(10);
  return <div className="service-admin"><header><span>商业服务</span><h1>购买与服务说明</h1><p>独立维护主体、联系方式、权益范围和协议。保存草稿后明确发布，不影响已购权益、价格或商户密钥。</p></header>{error&&<p className="service-error" role="alert">{error}<button disabled={busy} onClick={()=>{if(!dirty||window.confirm('重新载入将替换未保存的配置，是否继续？'))load();}}>重新载入</button></p>}{notice&&<p className="service-success" role="status">{notice}</p>}{!draft?<p>正在读取配置…</p>:<><nav className="service-tabs">{[['contact','主体与联系'],['scope','购买与售后'],['policies','协议正文']].map(([id,title])=><button key={id} disabled={busy} aria-pressed={section===id} onClick={()=>setSection(id)}>{title}</button>)}</nav><section className="support-panel"><p className="service-small">正式上线前请由运营方核实本页内容；基础说明不是自动生成的合规认证。未填写的联系信息不会被编造展示。</p><fieldset disabled={busy}>{visible.map(([key,title])=><label key={key}>{title}{section==='contact'?<input value={draft[key]} maxLength={1000} onChange={e=>setDraft(v=>({...v,[key]:e.target.value}))}/>:<textarea rows={key.endsWith('Body')?12:3} maxLength={key.endsWith('Body')?30000:key==='refundPolicy'?4000:1000} value={draft[key]} onChange={e=>setDraft(v=>({...v,[key]:e.target.value}))}/>}</label>)}</fieldset><div className="support-actions"><button disabled={busy||!dirty} onClick={()=>setDraft(data.draft)}>撤销修改</button><button disabled={busy||!dirty} onClick={save}>保存草稿</button><button className="service-primary" disabled={busy||dirty||data.version==='0'} onClick={publish}>发布说明</button></div><p className="service-small">{data.public.published?'前台使用已发布版本':'前台使用基础说明，正式信息待运营方完善'} · 草稿版本 {data.version}</p><ServiceLinks/></section>{data.history.length>0&&<details className="support-panel"><summary>已发布历史（最近 20 版）</summary>{data.history.map(h=><button disabled={busy} key={h.id} onClick={async()=>{if(dirty&&!window.confirm('用历史版本替换当前未保存输入？'))return;try{const r=await api(`/admin/service/history/${h.id}`);setDraft(r.draft);setNotice('已载入历史内容，保存并发布后才影响前台。');}catch(e){setError(e.message);}}}>载入 #{h.id} · {h.created_at}</button>)}</details>}</>}
  </div>;
}
export function AdminSupport(){
  const [items,setItems]=useState(null),[selected,setSelected]=useState(null),[status,setStatus]=useState(''),[reply,setReply]=useState(''),[nextStatus,setNextStatus]=useState('in_progress'),[busy,setBusy]=useState(false),[error,setError]=useState('');const key=useRef(crypto.randomUUID()),sending=useRef(false),revision=useRef(0);useDraftGuard(Boolean(reply),busy);
  const load=async()=>{const rev=++revision.current;try{const d=await api('/admin/support'+(status?`?status=${status}`:''));if(rev!==revision.current)return;setItems(d.items);setSelected(old=>old?d.items.find(x=>x.id===old.id)||old:null);setError('');}catch(e){if(rev===revision.current)setError(e.message);}};useEffect(()=>{load();return()=>{revision.current++;};},[status]);
  const send=async e=>{e.preventDefault();if(sending.current)return;sending.current=true;setBusy(true);setError('');try{const r=await api(`/admin/support/${selected.id}/replies`,{method:'POST',headers:{'If-Match':selected.version},body:JSON.stringify({message:reply,status:nextStatus,requestKey:key.current})});setSelected(r.item);setReply('');key.current=crypto.randomUUID();await load();}catch(e){setError(e.message);}finally{sending.current=false;setBusy(false);}};
  return <div className="service-admin"><header><span>人工服务</span><h1>售后申请管理</h1><p>仅管理员可处理。回复和状态不会自动退款、关闭交易、改价或授予课程权限。</p></header>{error&&<p className="service-error" role="alert">{error}<button disabled={busy} onClick={load}>重新载入</button></p>}<label>申请状态<select disabled={busy} value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{SUPPORT_STATES.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><div className="support-layout"><section className="support-panel"><header><h2>最近 100 条申请</h2><button onClick={load}>刷新</button></header>{items===null?<p>正在读取…</p>:!items.length?<p>没有匹配的申请。</p>:<div className="support-list">{items.map(item=><button key={item.id} aria-pressed={selected?.id===item.id} disabled={busy} onClick={()=>{if(reply&&!window.confirm('切换会清空未发送回复，是否继续？'))return;setSelected(item);setReply('');key.current=crypto.randomUUID();}}><span><b>{item.title}</b><small>#{item.id} · 账号 #{item.accountId} · {label(SUPPORT_CATEGORIES,item.category)}</small></span><em>{label(SUPPORT_STATES,item.status)}</em></button>)}</div>}</section><section className="support-panel">{!selected?<p>选择申请后查看说明并回复。</p>:<><h2>{selected.title}</h2>{selected.order&&<p>订单：{selected.order.orderNo} · {money(selected.order.amountCents)} · {selected.order.status}</p>}<Messages item={selected}/><form onSubmit={send}><fieldset disabled={busy}><label>官方回复<textarea required maxLength={4000} rows={5} value={reply} onChange={e=>{setReply(e.target.value);key.current=crypto.randomUUID();}}/></label><label>处理状态<select value={nextStatus} onChange={e=>{setNextStatus(e.target.value);key.current=crypto.randomUUID();}}>{SUPPORT_STATES.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><p className="service-small">“处理完成”不是退款到账状态；若款项已人工退回，请在回复中说明实际处理情况。</p><div className="support-actions"><button type="button" onClick={()=>setReply('')}>清空回复</button><button className="service-primary" disabled={!reply.trim()}>发送回复并更新状态</button></div></fieldset></form></>}</section></div></div>;
}
