import {useEffect,useRef,useState} from 'react';
import {api,getToken} from './api.js';
import './functional-hardening.css';
export function WorkspaceCapacity({identity}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false);
 const alive=useRef(true),working=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{let active=true;setData(null);setError('');if(open&&identity)api('/me/capacity').then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[open,identity]);
 const download=async()=>{if(working.current)return;working.current=true;setBusy(true);setError('');const token=getToken();try{let offset=0,snapshot='',result=null;const visited=new Set();do{if(!alive.current||getToken()!==token)throw Error('账号已变化，导出已停止。');if(visited.has(offset)||offset>1000)throw Error('导出分页异常，请重试。');visited.add(offset);const page=await api(`/me/export?offset=${offset}&snapshot=${snapshot}`);if(!alive.current||getToken()!==token)throw Error('账号已变化，导出已停止。');if(!result)result={format:page.format,exportedAt:page.exportedAt,workspace:page.workspace,notice:page.notice,learningNotes:[]};result.learningNotes.push(...page.learningNotes);snapshot=page.snapshot;offset=page.nextOffset;}while(offset!==null);const url=URL.createObjectURL(new Blob([JSON.stringify({...result,exportComplete:true},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='OneShowLearn-私人备份-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){if(alive.current&&getToken()===token)setError(e.message);}finally{working.current=false;if(alive.current)setBusy(false);}};
 if(!identity)return null;
 return <details className="private-capacity" onToggle={e=>setOpen(e.currentTarget.open)}><summary>私人记录容量与导出备份</summary>{error&&<p role="alert">{error}</p>}{data?<><p>空间 {Math.ceil(data.workspaceBytes/1024)} / {data.workspaceLimit/1024} KB；个人笔记 {data.usage.notes.used}/{data.usage.notes.limit}；成果 {data.usage.achievements.used}/{data.usage.achievements.limit}；任务 {data.usage.tasks.used}/{data.usage.tasks.limit}；关联收藏 {data.usage.contentFavorites.used}/{data.usage.contentFavorites.limit}；课时笔记 {data.learningNotes.used}/{data.learningNotes.limit}。</p><p>回收站及归档仍保留记录并计入容量；删除不等于释放空间。接近上限时先导出，平台不会自动清理你的内容。</p></>:<p>展开后读取当前账号实际容量。</p>}<button disabled={busy} onClick={download}>{busy?'正在导出…':'导出本人记录（包含回收站）'}</button><small>文件含私人内容，请妥善保管；导出不是自动云备份，不支持整包导入。</small></details>;
}
